### ISSUE TITLE
Hello world example

### ISSUE THREAD

**Issue by r00takaspin** [sdogruyol/kemal#104]
Hi, I am trying run hello world example [from tutorial](http://kemalcr.com/docs/getting_started/), but I am getting such error:

<pre>➜  kemal_example git:(master) ✗ crystal build src/kemal_example.cr -d
Error in ./libs/kemal/kemal.cr:21: instantiating 'HTTP::Server::Context#params()'

    image = env.params["image"]
                ^~~~~~

in ./libs/kemal/kemal/context.cr:6: instantiating 'Kemal::ParamParser#parse()'

      @params ||= Kemal::ParamParser.new(@request).parse
                                                   ^~~~~

in ./libs/kemal/kemal/param_parser.cr:17: instantiating 'parse_request()'

    parse_request
    ^~~~~~~~~~~~~

in ./libs/kemal/kemal/param_parser.cr:21: instantiating 'parse_url_params()'

    parse_url_params
    ^~~~~~~~~~~~~~~~

in ./libs/kemal/kemal/param_parser.cr:38: undefined method 'url_params' for Nil

    if params = @request.url_params
                         ^~~~~~~~~~

================================================================================

Nil trace:

  ./libs/kemal/kemal/param_parser.cr:12

      def initialize(@request)
                     ^

  ./libs/kemal/kemal/param_parser.cr:12

      def initialize(@request)
                     ^~~~~~~

  ./libs/kemal/kemal/param_parser.cr:12

      def initialize(@request)</pre>

Crystal version: Crystal 0.10.2 (Wed Jan 13 20:13:28 UTC 2016), OSX El Capitan

**Comment by jmoriau** [comment]
`Crystal version: Crystal 0.10.2`
This might be unrelated, but could you maybe try with the latest version of Crystal (0.12) ?

**Comment by sdogruyol** [comment]
You need at least Crystal 0.11.0

**Comment by r00takaspin** [comment]
@jmoriau @sdogruyol  Thank you, it works!
