### ISSUE TITLE
Examples with template rendering

### ISSUE THREAD

**Issue by fuzzthink** [sdogruyol/kemal#110]
New to ruby/crystal ecosystem, so don't know about ecr template. Googled it, found nothing. Can you please give provide source for the template and maybe a some examples?

thanks.

**Comment by sdogruyol** [comment]
Hey @fuzzthink 

I think this would be helpful for you http://kemalcr.com/docs/views/

**Comment by fuzzthink** [comment]
Thank you, but "ERB-like built-in ECR views" is too vague. Is ECR spec-for-spec the same as ERB, but just the file extension is different? (If so, why not just make it accept .ecr files?) Will it mirror the spec once ERB changes? If no to either of these, then ECR will need some documentation. 

thanks.

**Comment by sdogruyol** [comment]
Hey there, those are nice questions. I'm not sure if it follow ERB by spec for spec but it's quite alike.

You can easily read the ECR source here with great documentation https://github.com/manastech/crystal/blob/8cecd0808fb164ebd5a4c4de2624147814ce5e43/src/ecr/ecr.cr :+1:

**Comment by drujensen** [comment]
or here: http://crystal-lang.org/api/ECR.html

**Comment by sdogruyol** [comment]
@drujensen thanks a lot :smile:

**Comment by fuzzthink** [comment]
Thank you @drujensen.
@sdogruyol , please hyperlink that to "ecr" in both the frontpage and the views doc. As googling
"ecr crystal ruby web template"
"ecr crystal web template"
"ecr ruby web template"
gives nothing.

**Comment by drujensen** [comment]
@fuzzthink your welcome.  for a googling tip, i use `crystal lang` and then the term like `ecr`.

**Comment by sdogruyol** [comment]
Thanks @fuzzthink . I've updated the gh-pages accordingly :+1:
