### ISSUE TITLE
How to write files?

### ISSUE THREAD

**Issue by tmikaeld** [sdogruyol/kemal#111]
How do i write files? For example save a JSON response to disk?

**Comment by sdogruyol** [comment]
Hey there,

You can use `File.write` to do that. You can read the Crystal API for more info http://crystal-lang.org/api/File.html#write%28filename%2Ccontent%2Cperm%3D%3Cspanclass%3D%22t%22%3EDEFAULT_CREATE_MODE%3C%2Fspan%3E%2Cencoding%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%2Cinvalid%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%29-class-method

**Comment by tmikaeld** [comment]
Thanks, works very well!

Have never used ruby before but this got me started within seconds!
Can't wait to see more examples and features of both kemal and crystal.

**Comment by sdogruyol** [comment]
Thanks a lot :+1:
