### ISSUE TITLE
Trailing slash in URL route

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal#113]
Hi,

I have defined a **route** using 2 params (and the 2 is important this I have not the same behavior for 1 param URL)
~~~crystal
get "/:controller/:action" do |env|
  print env.params
end
~~~
that I call in `ruby`
~~~ruby
Curl.get("http://#{host}/test/param2'}
~~~
and `env.params` contains 
~~~crystal
{"controller/" => "test", "action" => "param2"}
~~~
instead of
~~~crystal
{"controller" => "test", "action" => "param2"}
~~~

**Comment by askn** [comment]
URL params are being parsed by Radix. Radix tree has a bug I think. @luislavena

**Comment by luislavena** [comment]
@waghanza @askn correct, appears to be a bug in Radix parsing:

```crystal
require "radix"

tree = Radix::Tree.new
tree.add "/:controller/:action", :my_route

result = tree.find "/products/featured"

if result.found?
  pp result.params # => result.params = {"controller/" => "products", "action" => "featured"}
end

Can you please open this at the repository?
https://github.com/luislavena/radix/issues

Thank you.

**Comment by sdogruyol** [comment]
@waghanza thanks for the report :+1: 
@askn thanks for the info :+1: 
@luislavena thanks for the response :+1:

**Comment by luislavena** [comment]
@waghanza @askn @sdogruyol this should be solved by `v0.1.1` of radix.

I recommend locking to that version on Kemal's `shard.yml` to force the update of anyone using Kemal right now.

Cheers.

**Comment by sdogruyol** [comment]
I'll release a minor version with this change. 

Thanks a lot @luislavena :+1:

**Comment by sdogruyol** [comment]
@waghanza you can use Kemal `0.9.3` as of now.
