### ISSUE TITLE
Failed using 0.9.3

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal#114]
Hi,

I see that v**version** `0.9.3` is available on github.

However, I can not use
~~~yaml
dependencies:
  kemal:
    github: sdogruyol/kemal
    version: 0.9.3
~~~
since I have an error
~~~sh
git command failed: git ls-tree -r --full-tree --name-only v0.9.3 -- shard.yml ()
~~~
Using **master** fix the problem

**Comment by sdogruyol** [comment]
Ouch. That's my mistake...i will fix that tomorrow!

Thanks

**Comment by waghanza** [comment]
Quick response :+1:
