### ISSUE TITLE
POST / PUT should not return 201 ?

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal#115]
Hello,

According to **REST** usage `PUT` / `POST` should return a **201** as **HTTP** status.

It return `200`.

Is it a wanted behavior ? or should I return a status code manually ?

Regards,

PS : I tested with a empty method

**Comment by sdogruyol** [comment]
@waghanza thanks for the info.

Actually by default `Kemal` returns 200 and we don't have any special cases for PUT / POST.

**Comment by waghanza** [comment]
@sdogruyol And should not it be 201 (according to REST standard) ?

**Comment by sdogruyol** [comment]
Well Rails also returns 200 for POST responses

**Comment by waghanza** [comment]
@sdogruyol yes, so as `flask` in python **world**, but you can apply cause it standard (to return a 201 in case of POST / PATCH), no ?

just open the debate ...

**Comment by sdogruyol** [comment]
This is open to debate :+1:

**Comment by sdogruyol** [comment]
WDYT?

@f @askn

**Comment by drujensen** [comment]
Status Code 201 means that a resource was created and will return the identity in the body.  Status Code 202 means that the request to create the request was accepted but might create the identify at a later time.

**Comment by waghanza** [comment]
perhaps, returning `204` for `POST`/`PUT`/`PATCH` for empty methods and recommend to return `201`

**Comment by f** [comment]
`200` is the most generic of `2XX` codes which makes sense in Kemal's context. Kemal is not a REST server but a WebServer. If you want to create a REST standard web api, you can simply change the status code of response explicitly in the body of route.

> `200`: Standard response for successful HTTP requests. The actual response will depend on the request method used. In a GET request, the response will contain an entity corresponding to the requested resource. In a POST request, the response will contain an entity describing or containing the result of the action

> `201`: The request has been fulfilled, resulting in the creation of a new resource.

Making it `201` implicitly sounds strange to me and `201` has a specific meaning *(created)* which is a result of a process **you decide**. **Kemal cannot know if the request is fulfilled, you can know if it is**.
