### ISSUE TITLE
Use production app

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal#116]
Hi,

According to crystal doc http://crystal-lang.org/docs/using_the_compiler/index.html, I can use `crystal build src/app.cr --release` to generate a production (**fully optimized**) build.

However, when I run `./app`, I have the **[development]** flag chown.

How can I release a production build ?

Regards,

**Comment by jmoriau** [comment]
I think the only difference for now is how the logger behaves, you can set the environment by passing it when launching the server.
In development, it logs everything to the console, and in production it logs everything to a file.

**Comment by waghanza** [comment]
and who can I pass the `env` ?

**Comment by jmoriau** [comment]
With `-e production`, you should read all the options with `-h`

**Comment by waghanza** [comment]
:+1:
