### ISSUE TITLE
Seting up a Rest API as a service

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal#117]
Hi all,

I try to build an API using `crystal` an `kemal`. 
I've created this restful api, everything is working, I mean when I start 
~~~sh
sudo /usr/local/bin/rest
~~~
I can **successfully** use my API.
However, when I want to start it via **start-stop-daemon**, it's fail.
I mean 
~~~sh
sudo start-stop-daemon --start --background --pidfile /run/rest.pid --exec /usr/local/bin/rest
~~~
I can't reach my API.
Does somebody has an idea ?

**Comment by sdogruyol** [comment]
I guess this is mostly related to your Operating System.

**Comment by waghanza** [comment]
i'm running latest debian

has anyone got the problem ?

**Comment by sdogruyol** [comment]
I've been running Kemal on Ubuntu 14.04 without any problem. 

The difference is that you are running your service under `/usr/local/bin/rest' with sudo. Probably start-stop-daemon doesnt have sudo rights to start Kemal process.

**Comment by waghanza** [comment]
when I run `ps`  or `netstat`, I can see that `kemal` is active

**Comment by waghanza** [comment]
I fact it was a path problem, the **404** was a general error outside of routes definition

**Comment by sdogruyol** [comment]
:+1:

**Comment by sdogruyol** [comment]
Meanwhile are you using Kemal for something public that we can see?

**Comment by waghanza** [comment]
not for the moment, but I plan to
