### ISSUE TITLE
Parameters validation

### ISSUE THREAD

**Issue by jmoriau** [sdogruyol/kemal#119]
Hi,

I needed to validate parameters for my API, so I built a middleware to do just that: https://github.com/jmoriau/kemal-parameters-validation

Let me know what you think :smile:

**Comment by sdogruyol** [comment]
This is something needed for security. So big thumbs for this plugin :+1: 

I wonder if we can pretty up the DSL though :question:

**Comment by jmoriau** [comment]
I know it's not super pretty, but it's the best I could think of, any ideas are welcome :/
