### ISSUE TITLE
Warning and deprecations for newer Radix

### ISSUE THREAD

**Issue by luislavena** [sdogruyol/kemal#128]
Hello @sdogruyol @f,

On luislavena/radix#5 and luislavena/radix#4 we identified an issue around usage of named parameters at the same level (which seems to be used by Kamber)

Due limitations of Radix tree, some style of routes are not possible.

I've released `v0.1.2` that presents a deprecation warning when routes like that are specified. Next version (`v0.2.0`) will raise error when attempt to use them.

Just wanted to FYI in case reports about that reach out here.

Cheers.

**Comment by f** [comment]
https://github.com/luislavena/radix/issues/5#issuecomment-195569978
