### ISSUE TITLE
Overrideable/adjustable option parsing

### ISSUE THREAD

**Issue by benjolitz** [sdogruyol/kemal#129]
I'm working on some prototypes to demonstrate the use case of Crystal.

One thing that has bitten me in the ass is both option parsing and #86 

While I can parse with the OptionParser quite easily, I cannot hijack the `--help` nor can I add to it without wiping out Kemal's options/help.

It would be fantastic if `Kemal::CLI` could call a passed in block or function that would operate on `|opts|`

**Comment by sdogruyol** [comment]
I'm not sure about what can be done for this (at least for now).

**Comment by benjolitz** [comment]
I've a proposed PR that allows one to merge additional options into the OptionParser via a block. I've found I can use it to explicitly set the fields of a modified Config class or use my own.

**Comment by benjolitz** [comment]
ping @sdogruyol

**Comment by sdogruyol** [comment]
Hey @benjolitz, how would someone add these options via command line? (or not)

**Comment by benjolitz** [comment]
The proposed PR suggests something like:
```
 config.on_options = ->(parser : OptionParser) {
      parser.on("--test TEST_OPTION", "Test an option") do |value|
        $test_option = value
      end
     parser.on("-a", "--another-option", "Another option) do
         # set some variable to indicate setting
        mymodule_instance.another_option = true
     end
  }
```

**Comment by sdogruyol** [comment]
Added as of https://github.com/sdogruyol/kemal/commit/212ea8707d511a5b8de870fcdc1b25f4d5a2cbaa
