### ISSUE TITLE
Rendering errors while using JSON content type

### ISSUE THREAD

**Issue by waterlink** [sdogruyol/kemal#130]
It simply returns the HTML as application/json and browser renders it as plain text.

Viable options:
- when failure is captured - change to `text/html` content type, or
- depending on current content type emit different representation of an error (in JSON's case is: `{error: "Something bad happened"}`).

**Comment by waterlink** [comment]
@sdogruyol Thanks! :)

**Comment by sdogruyol** [comment]
Thanks :+1:
