### ISSUE TITLE
Better file handler utilization for Logging

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [sdogruyol/kemal#131]
I suspect there is a memory leak somewhere within the normal get request handler (possibly others) when running under `Crystal 0.13.0 (Mon Mar  7 18:07:38 UTC 2016)` on osx 10.11.4. I have kemal version `0.11.1`.

Example server:

```
require "kemal"

get "/" do |env|
  "John"
end

Kemal.config.port = 3001
Kemal.run
```

I am hitting the server with [vegeta](https://github.com/tsenart/vegeta) with the following command (multiple times):

    echo "GET http://localhost:3001/" | vegeta attack -duration=50s -rate=3000 | tee results.bin | vegeta report

The memory usage keeps going up, and does not appear to ever be collected. After the first run it hovers at around 75MB, and goes up with 5-10 MB for each successive run of the vegeta command. Can this possibly be the logging that is causing it or can it be a memory leak somewhere?

**Comment by sdogruyol** [comment]
@stephan-nordnes-eriksen thanks for the report.

I'll have to replicate the tests to dig deeper. I use `wrk` for load testing and never seen a behaviour like this. 

What's the difference between `vegeta` and `wrk`?

**Comment by stephan-nordnes-eriksen** [comment]
Very interesting. Memory consumption is way lower with wrk, however the memory seems to go up by a bit each time i run wrk. Can the issue somewhere in the code related to when requests are being dropped? Because with vegeta you can set a `rate`, and mine was set to 3000, but with wrk i see that requests per second is less than 3k (~= 2.1k).

**Comment by sdogruyol** [comment]
So i've digged this up.

It's definitely related to `Logging`. 

First i ran `vegeta` with default options (which means the logging is on and outputs to STD). After some time the process ballooned to 75MB and then crashed with the following stacktrace.

```
Error accepting socket: Too many open files (Errno)
[4461462701] *Errno::new<String>:Errno +381
[4461588982] *Kemal::run:Nil +9574
[4461512037] main +22085
```

Later i turned off logging with `logging false` and the process stayed at 2Mb of ram with completing the benchmark.

**Comment by stephan-nordnes-eriksen** [comment]
I see. Is it then possible to have rolling logs in kemal to prevent this?

**Comment by sdogruyol** [comment]
What do you mean by rolling logs? (something like `logrotate`?)

**Comment by stephan-nordnes-eriksen** [comment]
Yeah, essentially that a log-file has a max number of lines and the oldest line is deleted/overwritten when that length has been reached.

But anyways, why is the memory increasing? Isn't the log dumped to the file? Why is it also kept in memory?

**Comment by sdogruyol** [comment]
The log is not written to a file in `development` mode which is the default mode.

**Comment by stephan-nordnes-eriksen** [comment]
I see, but it is in release mode?

**Comment by sdogruyol** [comment]
`--release` is not related to Kemal. It is used to turn on LLVM optimizations for Crystal

**Comment by stephan-nordnes-eriksen** [comment]
I just tested with ´env = "production`". When hitting the server it crashes almost immediately with:

```
Error accepting socket: Too many open files (Errno)
[4443735890] *CallStack::unwind:Array(Pointer(Void)) +82
[4443735793] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4443735752] *CallStack::new:CallStack +40
[4443819473] *Exception@Exception#initialize<Errno, String>:CallStack +33
[4443819395] *Errno#initialize<Errno, String>:CallStack +115
[4443819252] *Errno::new<String>:Errno +100
[4443967230] *TCPServer#accept<TCPServer>:TCPSocket +174
[4443906546] *HTTP::Server#listen<HTTP::Server>:Nil +146
[4443875504] *Kemal::run:Nil +624
[4443687196] __crystal_main +41196
[4443697400] main +40
```

**Comment by sdogruyol** [comment]
The error is pretty self descriptive i think `Error accepting socket: Too many open files (Errno)`.

What's your `ulimit -n` ?

**Comment by stephan-nordnes-eriksen** [comment]
It was a bit low (256), increasing it helped, but I still got the same error.

I feel that crashing the entire app because of this error is somewhat wrong anyway. This makes the webserver very sensitive to dos attacks. That is isn't that good for a "high performance web server". I tested with the native HTTP server, and I did not get the error with the same load after I increased my ulimit, but it did happen with the 256 limit.


```
require "kemal"

get "/" do |env|
  "John"
end

Kemal.config.env = "production"
Kemal.config.port = 3001
Kemal.run


# VS:

require "http/server"

server = HTTP::Server.new(3001) do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world! The time is #{Time.now}"
end

puts "Listening on http://0.0.0.0:3001"
server.listen

```

When hitting a similar sinatra app I get a bounch of dropped requests, but the app does not crash, which I believe is a preferable alternative.

**Comment by sdogruyol** [comment]
@stephan-nordnes-eriksen this is related to the current logging mechanism of `Kemal`. It definitely needs improvement.

If you want you can explicitly turn off the logging mechanism with `logging false` and rerun your benchmarks to see the difference.

Thanks for the report.

**Comment by sdogruyol** [comment]
I've come to conclusion that increasing `ulimit -n` is the only option since `Kemal` serves much more request compared to `Sinatra` thus needing more handler.
