### ISSUE TITLE
Trying to launch websockets 

### ISSUE THREAD

**Issue by TyanNN** [sdogruyol/kemal#134]
So when im trying to do even the simplest 

```crystal
ws "/" do |socket|

end
```
I get this:
```crystal
in ./libs/kemal/kemal/dsl.cr:10: instantiating 'Kemal::WebSocketHandler:Class#new(String)'

  Kemal::WebSocketHandler.new path, &block
                          ^~~

instantiating 'Kemal::WebSocketHandler#initialize(String)'

in /usr/lib/crystal/http/server/handlers/websocket_handler.cr:21: wrong number of arguments for '(HTTP::WebSocket, HTTP::Server::Context -> Nil)#call' (given 1, expected 2)
Overloads are:
 - (HTTP::WebSocket, HTTP::Server::Context -> Nil)#call(arg0 : HTTP::WebSocket, arg1 : HTTP::Server::Context)

        @proc.call(ws_session)
              ^~~~
```

Crystal 0.13, Manjaro

**Comment by waterlink** [comment]
Seems, like you need to update to latest Crystal version (`0.14.2`)

**Comment by TyanNN** [comment]
@waterlink the thing is that it's not yet available even in Manjaro testing reps. Well, i should probably wait 'til it gets there or download it manually.

**Comment by sdogruyol** [comment]
Hey @TyanNN you either need to use Kemal `v0.11.0` with Crystai `0.13.0`.

Or if available you need to update Crystal to latest stable version.

**Comment by sdogruyol** [comment]
@TyanNN you can specify a shard version within `shard.yml` like below.

```yaml
dependencies:
  kemal:
    github: sdogruyol/kemal
    version: 0.11.0
```

**Comment by TyanNN** [comment]
@sdogruyol
 ```yml
name: kemal
version: 0.11.1
```
```bash
 crystal --version
Crystal 0.13.0 (Mon Mar  7 19:51:32 UTC 2016)

```

**Comment by TyanNN** [comment]
@sdogruyol is 11.1 broken?

**Comment by sdogruyol** [comment]
@TyanNN it's for Crystal `0.14.1`+

**Comment by TyanNN** [comment]
@sdogruyol oh well, thanks. Downgraded it, works fine now.

**Comment by sdogruyol** [comment]
@TyanNN thank you :+1:

**Comment by TyanNN** [comment]
@sdogruyol oh.. now i get a lot of `embed_ecr` is deprecated, use `ECR.embed`, what should i do with it?

**Comment by sdogruyol** [comment]
@TyanNN for now we just ignore it because the view template engine is not yet updated (https://github.com/jeromegn/slang)

**Comment by TyanNN** [comment]
anyway, i'll just use AUR version, it should be fine
