### ISSUE TITLE
Is it possible to configure headers for assets to allow caching. 

### ISSUE THREAD

**Issue by elorest** [sdogruyol/kemal#137]

**Comment by sdogruyol** [comment]
For now there isn't anything like that for static files.

However you can do something like this

```
before_all do |env|
  env.response.headers.add "Cache-control", "public"
end
```

P.S: This will add cache for all.

**Comment by isaacsloan** [comment]
Thanks. Would there be a way to do something like
    before "/assets/*" do |env|

**Comment by ukd1** [comment]
@sdogruyol @isaacsloan if you have access to the env in the ``before_all`` you could match against the request uri?

**Comment by sdogruyol** [comment]
@ukd1 @isaacsloan currently `before` filters does not work on anything other than routes.

**Comment by sdogruyol** [comment]
Related issue https://github.com/crystal-lang/crystal/pull/2470

**Comment by gottlike** [comment]
Only slightly related to this issue, but: Is there a way to set custom headers per route?

**Comment by sdogruyol** [comment]
@gottlike sure something like this is possible.

```
get "/route1" do |env|
  env.response.headers.add "Some Header", "Some Value",
  "Response from 1"
end

get "/route2" do |env|
  env.response.headers.add "Another Header", "Another Value",
  "Response from 2"
end
```

**Comment by gottlike** [comment]
Cool, thanks for the quick reply!
