### ISSUE TITLE
Kemal's documentation incorrect regarding 'content_type'

### ISSUE THREAD

**Issue by ruivieira** [sdogruyol/kemal#138]
In [Kemal's website ](http://kemalcr.com/docs/http-requests/), the HTTP request documentation is incorrect.

It shows 
```crystal
# Set the content as application/json and return JSON
get "/user.json" do |env|
    kemal = {name: "Kemal", language: "Crystal"}
    env.content_type = "application/json"
    kemal.to_json
end
```

but it should be

```crystal
# Set the content as application/json and return JSON
get "/user.json" do |env|
    kemal = {name: "Kemal", language: "Crystal"}
    env.response.content_type = "application/json"
    kemal.to_json
end
```

**Comment by sdogruyol** [comment]
Nice catch :+1: Could you please open a PR for this :bow:

**Comment by sdogruyol** [comment]
@ruivieira meanwhile this is in `gh-pages` branch of this repo.

**Comment by ruivieira** [comment]
@sdogruyol thanks. I've made the [PR](https://github.com/sdogruyol/kemal/pull/139) for `gh-pages`.

**Comment by sdogruyol** [comment]
Fixed via https://github.com/sdogruyol/kemal/pull/139
