### ISSUE TITLE
Async request?

### ISSUE THREAD

**Issue by dimparf** [sdogruyol/kemal#142]
Hi
Kemal is async web framework or blocking?

**Comment by sdogruyol** [comment]
@dimparf hello and welcome.

Could you please explain what do you mean by Async?

**Comment by dimparf** [comment]
One thread per request or one thread for all requests and sequential request processing?
Incoming request --> create thread, process request, send response.
or
Incoming request -> use thread, block incoming requests (stay in queue), process request, send response.

**Comment by sdogruyol** [comment]
Actually Crystal uses `Fiber`s (which are lightweight threads) for each request. So that's async and achieved by `spawn`. (which is like goroutines in golang).

Here's an example for `spawn`.

```crystal
spawn do
  puts "This is async"
end
```

Hope this helps.

**Comment by dimparf** [comment]
Thanks sdogruyol!

**Comment by sdogruyol** [comment]
You're welcome @dimparf 👍
