### ISSUE TITLE
How to implement custom error handling?

### ISSUE THREAD

**Issue by gottlike** [sdogruyol/kemal#143]
Does Kemal support such a thing as the following Sinatra code?

```ruby
error 400..510 do
  ...
end
```

I'd like to define custom error pages or behaviours, instead of serving the hardcoded HTML error pages.

**Comment by sdogruyol** [comment]
No but you can achieve the same behaviour like below. Unfortunately you need to specify view for each error. (maybe you can use a macro for that)

```crystal
def render_403(context)
  error = "Your custom page"
  context.response.write error
end
```

**Comment by gottlike** [comment]
Ah, okay. That will do for the moment.. but it might be a good feature for a future version ;)

**Comment by InstanceOfMichael** [comment]
where do you put this code?
