### ISSUE TITLE
Can't infer the type of instance variable '@route_lookup' of HTTP::Server::Context on Crystal 0.16.0

### ISSUE THREAD

**Issue by ruivieira** [sdogruyol/kemal#145]
Crystal 0.16.0 is throwing this error:

> Error in ./src/rv.cr:97: instantiating 'HTTP::Server::Context#params()'
> 
>   id = env.params.url["id"].to_i
>            ^~~~~~
> 
> in ./libs/kemal/kemal/context.cr:6: instantiating 'route_lookup()'
> 
>       @request.url_params = route_lookup.params
>                             ^~~~~~~~~~~~
> 
> in ./libs/kemal/kemal/context.cr:16: Can't infer the type of instance variable '@route_lookup' of HTTP::Server::Context
> 
> The type of a instance variable, if not declared explicitly with
> `@route_lookup : Type`, is inferred from assignments to it across
> the whole program.
> 
> The assignments must look like this:
> 
>   1. `@route_lookup = 1` (or other literals), inferred to the literal's type
>   2. `@route_lookup = Type.new`, type is inferred to be Type
>   3. `@route_lookup = Type.method`, where `method` has a return type
>      annotation, type is inferred from it
>   4. `@route_lookup = arg`, with 'arg' being a method argument with a
>      type restriction 'Type', type is inferred to be Type
>   5. `@route_lookup = arg`, with 'arg' being a method argument with a
>      default value, type is inferred using rules 1, 2 and 3 from it
>   6. `@route_lookup = uninitialized Type`, type is inferred to be Type
>   7. `@route_lookup = LibSome.func`, and `LibSome` is a `lib`, type
>      is inferred from that fun.
>   8. `LibSome.func(out @route_lookup)`, and `LibSome` is a `lib`, type
>      is inferred from that fun argument.
> 
> Other assignments have no effect on its type.
> 
> Can't infer the type of instance variable '@route_lookup' of HTTP::Server::Context
> 
>       @route_lookup ||= Kemal::RouteHandler::INSTANCE.lookup_route(@request.override_method as String, @request.path)
>       ^~~~~~~~~~~~~

`crystal --version`

> Crystal 0.16.0 (Thu May  5 18:33:34 UTC 2016)

in OS X 10.11.4 (15E65)

**Comment by ruivieira** [comment]
Forgot to add: Kemal in shard.yml is set to `master`

**Comment by sdogruyol** [comment]
Hey there,

I've just updated master with error-handler branch which adds 0.16.0 support.

Can you try again?

**Comment by ruivieira** [comment]
Thanks. It works fine.

However, if I delete `.shards` and `.crystal` in my own repo and do `crystal dep; crystal run` it doesn't work.

If I clone my repo to somewhere else, and do the above, it does work (but that's not a Kemal issue).

**Comment by sdogruyol** [comment]
Try

```
shards update
crystal src/your_app.cr
```

**Comment by ruivieira** [comment]
Works perfectly. Thanks.
