### ISSUE TITLE
Optional parameters or wildcards on routing

### ISSUE THREAD

**Issue by BatuhanK** [sdogruyol/kemal#149]
Is it possible (how if it's) to create an optional parameter or wildcards when routing?

**Comment by sdogruyol** [comment]
You can do something like this.

```crystal

get "/**" do
  "Matches everything except index"
end
```

**Comment by vectorselector** [comment]
is this in the guide?

**Comment by Blacksmoke16** [comment]
@kazzkiq The root of the app, i.e. nothing after the domain name.

For example:  `/*` would match `api.example.com/user` or `api.example.com/users/1` or `api.example.com/any/path`

but would _not_ match `api.example.com`

**Comment by benbonnet** [comment]
it feels exclusive; meaning by that, unable to use safely; it works randomly once other routes exists
is the following possible :
```
get "/first/one" {}
get "/second/one" {}
get "/*" { ...fallback for anything except "/" }
get "/" { ...homepage }
```
