### ISSUE TITLE
Accessing Kemal environment outside of routes

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/kemal#150]
This fails.

```crystal
Kemal.config.env = "production"

puts Kemal.config.env #=> "development"

get "/" do |env|
  puts Kemal.config.env #=> "production
end
```

It should report the environment as `production` in global scope.

**Comment by jasoncharnes** [comment]
@sdogruyol is there anymore info on this? I tried doing this and when I get to the first `puts Kemal.config.env` it's returning production. I tried this against the master `Kemal` and I'm using `Crystal 0.17.4 (2016-05-26)`

I'd love to help with this if I can.

**Comment by sdogruyol** [comment]
Thanks for the report @jasoncharnes 🙏🏻

Seems like it's related to Crystal `0.17.3`. Updating to `0.17.4` solved the issue 👍🏻
