### ISSUE TITLE
Streaming responses

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/kemal#151]
`stream` keyword for Server Sent Events with `text/event-stream` content type.

```crystal
stream "/keep_open" do |env|
  context.response.puts("Hello world!")
end
```

Thanks @asterite for the tips 👍

**Comment by sdogruyol** [comment]
Well seems like we dont necessarily need that.

This already does the trick


```crystal
get "/stream" do |env|
  loop do
    sleep 0.1
    env.response.print "Stream"
    env.response.flush
  end
  # Send the response first
  env
end
```

**Comment by asterite** [comment]
@sdogruyol Great, much simpler than adding another method! 🎉

**Comment by sdogruyol** [comment]
@asterite thank you 🙇

**Comment by rdp** [comment]
Is it possible to "flush" a stream from within the heart of a template?
