### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by mperham** [sdogruyol/kemal#153]
If I write a Kemal app, how do I test endpoints?  Sinatra supports Rack::Test so I can do this:

```ruby
describe "sidekiq web" do
  include Rack::Test::Methods

  it "can display scheduled" do
    get "/scheduled"
    assert_equal 200, last_response.status
    assert_match(/found/, last_response.body)
    refute_match(/HardWorker/, last_response.body)

    add_scheduled

    get "/scheduled"
    assert_equal 200, last_response.status
    refute_match(/found/, last_response.body)
    assert_match(/HardWorker/, last_response.body)
  end
end
```

**Comment by sdogruyol** [comment]
Hey there,

I should document this. There's https://github.com/sdogruyol/spec-kemal which does the job but not as complete as Rack::Test

**Comment by mperham** [comment]
sorry, I meant to send you a PR to add this but it's not just an edit of an existing page - requires a new doc/ markdown file.

**Comment by sdogruyol** [comment]
I'll ping you up when i add the new page then 👍  Thanks!
