### ISSUE TITLE
Any way to use instance variables?

### ISSUE THREAD

**Issue by mperham** [sdogruyol/kemal#155]
Kemal defines its routes at the top level so I have to include any helper methods at that level.  The issue is that instance variables can't be used at the top level to memoize computed values:

```ruby
module WebHelpers
  def locale
    @locale ||= lots_of_locale_logic || "en" # <========
  end
end

include WebHelpers

get "/" do |env|
  render("something.ecr")
end
```

something.ecr
```
Your current locale: <%= locale %>
```

Any suggestions on how to redesign my rendering to work better with Crystal and Kemal?  Should I instead mix in my helpers into `env`'s class and access that from my templates?

something.ecr
```
Your current locale: <%= env.locale %>
```

**Comment by sdogruyol** [comment]
For now mixing your helpers to `env` seems like the best option. Since `env` only lives through that request / response cycle it should be safer to do so.
