### ISSUE TITLE
Remove logging code?

### ISSUE THREAD

**Issue by mperham** [sdogruyol/kemal#159]
IMO Kemal shouldn't control logging output based on environment.  You might be interested in reading about ["modern" style Linux daemons](http://0pointer.de/public/systemd-man/daemon.html#New-Style%20Daemons), in summary:

1. Log to STDOUT only.
2. Shutdown on TERM.
3. Reload config on HUP.
4. Don't fork or daemonize yourself.

If you want to disable logging, you should provide a `-v` verbose flag that instead will configure the logging level.  Commonly you can set default level to WARN, have "-v" go to INFO and have "-v -v" go to DEBUG.  If you stick with these rules, the init system (upstart/systemd) can control log output and provide process monitoring, automatic log rotation, etc.

**Comment by sdogruyol** [comment]
@mperham i'm curious about this. For example how is sidekiq achieving this?

**Comment by mperham** [comment]
Sidekiq logs with a Logger but only to stdout.

**Comment by sdogruyol** [comment]
I've started rewriting the `CommonLogHandler` and came to conclusion that reducing https://github.com/sdogruyol/kemal/blob/master/src/kemal/common_log_handler.cr#L8-L14 to STDOUT will definitely make things simpler.
