### ISSUE TITLE
websockets and named parameters

### ISSUE THREAD

**Issue by mose** [sdogruyol/kemal#160]
I'm trying to use a named parameter with a websocket route, but it seems not to work, is there a reason for that? Or am I doing it wrong?

This works:
```
ws "/r/123" do |socket, env|
  pp env
  ...
end
```
```
env = #<HTTP::Server::Context:0x2793240 ...>
```

But this doesn't
```
ws "/r/:room" do |socket, env|
  pp env
  ...
end
```
```
2016-06-12 03:45:03 +0800 404 GET /r/123 - 173.9µs
```

(same works fine with a `get`)

**Comment by MGerrior** [comment]
Hey @mose , looking at the DSL [here](https://github.com/sdogruyol/kemal/blob/master/src/kemal/dsl.cr#L9), it doesn't look like named parameters in routes are supported by `kemal` at this time. It looks like based off [this line](https://github.com/sdogruyol/kemal/blob/master/src/kemal/websocket_handler.cr#L9) the websocket path needs to match one to one to be triggered, so no named parameters, just paths like "/r/123".

**Comment by mose** [comment]
Well, that's too bad. Fortunately I found a workaround by using a query, I think, with something like that:

In my react:
```
var server = new WebSocket("ws://" + location.hostname + ":" + location.port + "/ws?room=" + location.pathname.split('/').reverse()[0]);
```

then in Kemal
```
get "/room/:id" do |env|
  ...
end

ws "/ws" do |socket, env|
  pp env.params.query["room"]
  # use the sockets pool for that room
  ...
end
```

**Comment by sdogruyol** [comment]
@mose i'm aware of this issue and this is on the planned improvement list.

Thanks for the issue 👍

**Comment by sdogruyol** [comment]
Well, i think i'm gonna drop this for now.
