### ISSUE TITLE
Kemal (or/and Crystal) is slow!

### ISSUE THREAD

**Issue by ababich** [sdogruyol/kemal#169]
Excuse me for a bit provocative subject but the issue seems very important [as for me]

# Precondition

I created few implementations of tiny JSON URL Shortener backends to make a comparison
and I wanted to do the same with shiny brilliant Crystal/Kemal to check how it will compete with old MRI Ruby (2.3.1, well, not so old)

# Competition

* `puma` defaults with `rails 5 RC2` API application (on `MRI 2.3.1`) - not published
* `puma` defaults with  `roda 2.15.0` (on `MRI 2.3.1`) - https://github.com/ababich/tubity-roda
* `--release` compiled binary run in `-e production` mode of `kemal commit 0c46bd65` on `Crystal 0.18.4` https://github.com/ababich/tubity-crystal

# Implementation

"Business logic" is similar in all implementations - you can check out repos above

# Benchmark

Use `bench-rest` (https://github.com/jeffbski/bench-rest/)

With config like this (*this is for KEMAL*, for puma you need to change `port` and probably `url` to generate new keys):
```js
var benchrest = require('bench-rest');

var flow = {
  main: [
    { post: 'http://localhost:3000/s', json: {'url': 'http://mydata_kemal_#{INDEX}'} },
  ]
};
module.exports = flow;

benchrest(flow, { iterations: 10, limit: 100})
  .on('error', function (err, ctxName) { console.error('Failed in %s with err: ', ctxName, err); })
  .on('progress', function (stats, percent, concurrent, ips) {
    console.log('Progress: %s complete', percent);
   })
  .on('end', function (stats, errorCount) {
    console.log('error count: ', errorCount);
    console.log('stats', stats);
   });
```

With single polling:
`bench-rest -c 1 -n 100000 ./tubity.js`

And concurrency:
`bench-rest -c 16 -n 100000 ./tubity.js`

On `MacBook Pro (Retina, 15-inch, Mid 2014), 2.2Ghz i7 + 16Gb RAM`

# Results

## Concurrent requests

 | rails5 | roda | kemal | comment
------------ | ------------- | ------------- | ------------- | -------------
rpm, mean | 712.68 | 1981.12 | 1836.13 | more is better
resp, mean | 22.32 | 7.97 | 8.54 | time, ms, less is better
resp, median | 20.12 | 6.94 | 8.24 |
resp, 95% | 38.15 | 14.84 | 19.47 |
resp, 99.9% | 90.56 | 46.8 | 46.02 |

## Non-concurrent requests

For non-concurrent requests the result are similar
in terms that Roda is even faster by a margin

# Discussion

Redis does not seem to be a bottleneck, according to crystal-redis perf report (https://github.com/stefanwille/crystal-redis)

So, the bottleneck may be Kemal, or Crystal
Please, advise

# Questions

Is Crystal slow?
Is Kemal slow?
What am I doing wrong?

**Comment by sdogruyol** [comment]
This seems interesting. I need to check it myself first.

**Comment by sdogruyol** [comment]
Neither `Crystal` nor `Kemal` is slow. It's `bench-rest` that is slow. 

Even returning an empty response it can't max out a `Kemal` process and can only do around 1.7 - 1.8k rps (which is your max also).

I've written a simple `Crystal` program to benchmark with 100000 request.

```crystal
# tubity-bench.cr
require "http"
require "json"

client = HTTP::Client.new "127.0.0.1", port: 3000

100000.times do |index|
  client.post "/s", headers: HTTP::Headers{"Content-Type" => "application/json"}, body: {url: "http://mydata_kemal_#{index}"}.to_json
end
```

To run 

```crystal build --release tubity-bench.cr && ./tubity-bench```

It takes around 11 seconds

```
./tubity_bench  1.24s user 1.82s system 27% cpu 11.097 total
```

So that makes it around 9000 RPS.

**Comment by ababich** [comment]
Thanks for your consideration, will need to create JSON bench in crystal
unless you know any good benchmark we can use

**Comment by sdogruyol** [comment]
There's `cryload` https://github.com/sdogruyol/cryload but it only support `GET` requests for now :(
