### ISSUE TITLE
A bit of missing installation information for beginners

### ISSUE THREAD

**Issue by ilatif** [sdogruyol/kemal#17]
Hi @sdogruyol,

Thanks for writing such an awesome yet simple framework. I' am learning Crystal and I stumble upon `kemal` while searching for some web development frameworks which I can use and contribute to. I just want to point-out a small thing in installation section. I didn't knew what `shards` is until I see a video presentation from `Eurucamp 2015` but even then I struggled a bit while installing `kemal`. You mentioned in installation section to `include` a code snippet in `shard.yml` but putting that code was not running for me and I was getting following error:

    Shards::ParseError: missing required attribute: name at 4:0

     1.     github: sdogruyol/kemal
     2.     branch: master`

I did a little research and found out that every `shard.yml` must contain a `name` attribute. It would be nice if we have this mentioned in installation section of `kemal` as well so that beginners don't find it difficult to install it :-).

If you think adding that is not necessary then it's fine as well, I just wanted to get in-touch regarding this thing and I' am really looking forward to contribute to `kemal` soon :-).

Thanks.

**Comment by waterlink** [comment]
@ilatif `name` attribute is not a part of `kemal` dependency, rather it should be part of your `shard.yml` to begin with (it is the name of your application/library).

Shards is official package manager for Crystal, you can find, how your valid `shard.yml` should look like here: https://github.com/ysbaddaden/shards#usage

**Comment by sdogruyol** [comment]
Hey @ilatif 

Thanks for your kind words. You are right from a beginner's perspective. On the other hand @waterlink is correct about ```shards```usage.

I'll update the README to be more helpful for newcomers :+1:

**Comment by ilatif** [comment]
@waterlink: Thanks for your reply. I strongly agree with you that `name` thing has nothing to do with `kemal`. But since most beginners looking for web-development in Crystal don't know what `shards` is, having `name` mentioned explicitly in installation section will help them a lot.

@sdogruyol: Thanks for considering my suggestion :+1:.


Regards.

**Comment by sdogruyol** [comment]
@ilatif I'm closing this issue and going to add the required info to README :+1:

**Comment by ilatif** [comment]
@sdogruyol: Awesome. Thanks :+1:.
