### ISSUE TITLE
Initially confusing performance documentation

### ISSUE THREAD

**Issue by brandondrew** [sdogruyol/kemal#171]
Kemal's performance is absolutely _astonishing_.  But it took me a couple of seconds to realize that.

When I first saw the performance comparison, I didn't notice that response times were in different units.  I looked at the numbers and thought "how can Kemal handle _so many_ more requests per second, but still have longer response times?"  Of course after a second or two I noticed the solution: Kemal's speed was listed in _micro_ seconds rather than _milli_seconds.  

I think it would be more immediately clear if either microseconds or milliseconds were used for both, since the purpose of the table is to allow easy comparison.

I realize that the case can be made to use microseconds when they are the best fit for the number, and milliseconds when _they_ are the best fit for the number.  So each listing makes sense _in isolation_.  But since they are not displayed in isolation, I think it makes even more sense to use the same unit for both.

This is a little bit like the situation when listing files in a directory.  `ls -lh` is better for a readable size for any particular file.  But if you want to compare file sizes easily, then `ls -l` will make that much easier.

**Comment by sdogruyol** [comment]
I've just converted the benchmark times to `ms`. Thank you 👍
