### ISSUE TITLE
Error in ./src/your_app while requiring kemal

### ISSUE THREAD

**Issue by resethread** [sdogruyol/kemal#176]
Hey,
I'm trying to test crystal and kemal but I have a problem.
I can initialize a new project, install the dependencies in the file shard.yml, but after that, a simple require makes problems. 
You can look the error message : 

Error in ./src/your_app.cr:1: while requiring "kemal"
require "kemal"
^

in ./libs/kemal/kemal.cr:1: while requiring "./kemal/*"

require "./kemal/*"
^

in ./libs/kemal/kemal/route_handler.cr:2: while requiring "radix"

require "radix"
^

in ./libs/radix/radix.cr:1: while requiring "./radix/tree"

require "./radix/tree"
^

in ./libs/radix/radix/tree.cr:1: while requiring "./node"

require "./node"
^

Syntax error in ./libs/radix/radix/node.cr:77: unexpected token: = (expected ',' or ')')

    def initialize(@key : String, @payload : T? = nil, @placeholder = false)

Can you tell me what's wrong ?
Thanks.

**Comment by sdogruyol** [comment]
Hey there, thanks for trying out Kemal.

Could you please tell your

- Crystal version
- Kemal version
- Operating System

**Comment by resethread** [comment]
Crystal: 0.11.1
Kemal: lastest
OS: Ubuntu

**Comment by sdogruyol** [comment]
@resethread seems like your Crystal version is old.

Can you Crystal update to `0.18.x`?

**Comment by resethread** [comment]
Done.
I've a new error message : 

Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libssl' found
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status

**Comment by sdogruyol** [comment]
Seems like you are missing dependencies for Crystal.

You can check this wiki for your OS. https://github.com/crystal-lang/crystal/wiki/All-required-libraries

**Comment by resethread** [comment]
Yes that works.
Thank you :)

**Comment by sdogruyol** [comment]
👍
