### ISSUE TITLE
Static File Caching

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/kemal#179]
Some basic caching of static files.

- Cache-control
- Expires

**Comment by f** [comment]
I'll handle this. I need to strengthen my Crystal muscles :) They are weak for a while.

**Comment by sdogruyol** [comment]
💪

**Comment by f** [comment]
We need a fez emoticon reaction.

**Comment by sdogruyol** [comment]
Wish @github had custom emoticon support like slack 😢

**Comment by f** [comment]
@github Hear our voice!

**Comment by fernandes** [comment]
global custom emoticons? I can wonder the chaos... hahahah

**Comment by crisward** [comment]
I've added etags with this [pull request](https://github.com/sdogruyol/kemal/pull/204) - perhaps can be used to partially attain this goal. Didn't notice this until after I did it. Just trying to get gzip of static assets working. Still needs some work, tidying, squashing etc... Feedback welcome.

**Comment by sdogruyol** [comment]
Closing with https://github.com/sdogruyol/kemal/pull/204. Thanks @crisward 👍
