### ISSUE TITLE
undefined constant OpenSSL::SSL::Context::Server

### ISSUE THREAD

**Issue by Angarsk8** [sdogruyol/kemal#180]
Hi,

I'm following the [getting started guide](http://kemalcr.com/docs/getting_started/) and when I try to build my app, I get an error with this stack trace:

```
Error in ./libs/kemal/kemal/config.cr:6: undefined constant OpenSSL::SSL::Context::Server
@ssl : OpenSSL::SSL::Context::Server?
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The code I'm trying to compile is:

```crystal
# src/app.cr
require "kemal"

get "/" do
  "Hello World!"
end

kemal.run
```

What does that message mean at all? What am I doing wrong? 

thanks,

**Andrés**

**Comment by sdogruyol** [comment]
Please be sure to have Crystal 0.18.x

**Comment by Angarsk8** [comment]
Indeed it was that. I have updated Crystal and it works now

Thanks

**Comment by Angarsk8** [comment]
Hi @sdogruyol,

When I try to follow the guides on the [filter](http://kemalcr.com/docs/filters/) section, I get an error that says `undefined method 'content_type' for HTTP::Server::Response` whenever a try to run the app.

Do you know why is that? How could I fix this?

By the way, I'm using the exact same code that is on the guides

**Comment by sdogruyol** [comment]
Well, that should work, you are supposed to access the `response` like.

```crystal
# get
env.response.content_type
# set 
env.response.content_type = "application/json" 
```
