### ISSUE TITLE
How to use variables inside templates

### ISSUE THREAD

**Issue by Angarsk8** [sdogruyol/kemal#181]
Hi,

I've been trying to iterate over variables inside `.ecr` templates with no success. The code I have looks like this:

```crystal
...
get "/" do 
  todos = [{text: "foo"}, {text: "bar"}, {text: "foobar"}]
  render "src/views/home.ecr", "src/views/layout.ecr
end
...
```

```ecr
...
<div class="panels-wrapper">
  <% todos.each do |todo| %>
    <%= todo.text %>
  <% end %>
</div>
...
```

The exception looks like this:

```
Error in ./src/app.cr:16: expanding macro

  render "src/views/home.ecr", "src/views/layout.ecr"
  ^~~~~~
....
```

Can anybody help me with this?

Thanks,

**Andrés**

**Comment by cbortz** [comment]
Hey @Angarsk8. I am not a contributor, nor am I well versed in the Crystal language. I am a Ruby nerd though. From the information you've provided, it looks to be a syntax error. The following line is missing a closing quotation mark:

```crystal
render "src/views/home.ecr", "src/views/layout.ecr
```

If this is indeed the issue, then there _is_ a different bug: the exception shows the line with proper syntax, when it shouldn't.

**Comment by sdogruyol** [comment]
Nice catch @cbortz. I just opened https://github.com/crystal-lang/crystal/issues/3003.

**Comment by Angarsk8** [comment]
Sorry 😲, that was indeed the problem I catched it yesterday...

```crystal
get "/" do 
  todos = notes.map { |note_str|  Note.from_json(note_str) }
  render "src/views/home.ecr", "src/views/layout.ecr"
end
```

Thanks,

**Comment by sdogruyol** [comment]
@Angarsk8 could you please tell us your Crystal version for this issue?
