### ISSUE TITLE
Multiple tmp files of the same name

### ISSUE THREAD

**Issue by jwoertink** [sdogruyol/kemal#182]
I'm not sure if this is Kemal that does this directly, or if it's actually in the crystal lang, but when you boot a kemal app locally, you get a tmp file.

```crystal
#app1/app.cr
require "kemal"
get("/") { "app 1" }
Kemal.config.port = 3001
Kemal.run
```
From this app, you'll get a tmp file at `~/.cache/crystal/crystal-run-app.tmp`

```text
$ ps aux | grep crystal
jeremywoertink  30540   0.0  0.0  2434840    796 s004  S+   11:12AM   0:00.00 grep crystal
jeremywoertink  29839   0.0  0.0  2485556   2212 s004  S    10:50AM   0:00.02 /Users/jeremywoertink/.cache/crystal/crystal-run-app.tmp
jeremywoertink  29458   0.0  1.0  2691440 175544 s004  S    10:50AM   0:01.71 crystal app.cr
```

Booting a second one where the main file is the same name will result in 2 processes of the same name, but only 1 temp file. Somehow, they both still seem to run and respond.

```crystal
#app2/app.cr
require "kemal"
get("/") { "app 2" }
Kemal.config.port = 3002
Kemal.run
```

```text
$ ps aux | grep crystal
jeremywoertink  30540   0.0  0.0  2434840    796 s004  S+   11:12AM   0:00.00 grep crystal
jeremywoertink  29839   0.0  0.0  2485556   2212 s004  S    10:50AM   0:00.02 /Users/jeremywoertink/.cache/crystal/crystal-run-app.tmp
jeremywoertink  29840   0.0  0.0  2485557   2212 s004  S    10:50AM   0:00.02 /Users/jeremywoertink/.cache/crystal/crystal-run-app.tmp
jeremywoertink  29458   0.0  1.0  2691440 175544 s004  S    10:50AM   0:01.71 crystal app.cr
```
Notice here that there are 2 processes with the same name, but if you look in the `~/.cache/crystal/` folder, there's only 1 `crystal-run-app.tmp` file.

**Comment by sdogruyol** [comment]
Oh, this is Crystal doing caching when you just run your project with

```
crystal run your_app.cr
```

For production you should definitely compile and run your native binary like 

```
crystal build --release your_app.cr
./your_app
```

then you'll see that you only have 1 process :)

**Comment by jwoertink** [comment]
Yeah, for production it'll be a bit different, but locally, there's still more than 1. This issue comes up for me when I want to find that parent process to kill kemal, but doing a grep returns 2 PIDs. I don't know which one belongs to the one I'm trying to kill since they're both named the same. 

I have a giant rails app being ported over that's currently broken out in to a SOA structure. I'll end up having about 7 kemal apps running locally at the same time, and having 7 processes with the same name will cause conflicts. 

Maybe there's a way to just append some number to it?

**Comment by sdogruyol** [comment]
Killing this would be OK it will kill all the child processes

```
jeremywoertink  29458   0.0  1.0  2691440 175544 s004  S    10:50AM   0:01.71 crystal app.cr
```

**Comment by jwoertink** [comment]
`crystal app.cr` is the child process. The other one is the parent process. Killing the `crystal app.cr` process will stop kemal, but when trying to reboot, it throws a "address already in use" error.

**Comment by sdogruyol** [comment]
Why don't you use the QUIT signal `CTRL-C`?

**Comment by jwoertink** [comment]
I'm not sure how to do that from https://github.com/jwoertink/guard-kemal/blob/master/lib/guard/kemal.rb#L16

**Comment by sdogruyol** [comment]
Now that's interesting 👍 Maybe we better ask @asterite about how to handle those `tmp` processes?

**Comment by jwoertink** [comment]
I noticed I do have some other tmp processes with some numbers. One is called `crystal-run-play-1-15.tmp`. I'm not sure what that was from, but there's a few of them with different numbers. I'm assuming at some point it knew to make different ones.

**Comment by asterite** [comment]
When you do `crystal app.cr` Crystal will compile your project to a temporary file and then execute that, without replacing the compiler's process. If we replace the compiler's process then there will be just one binary executing.

An alternative solution is to do `crystal build app.cr` and then `./app`. Then just `app` will run.

I personally don't think this is an "issue", when you deploy or deliver you app you'll just have the executable.

Also, if you use Go and do `go run ...` exactly the same thing happens. I really wouldn't worry about this.

**Comment by asterite** [comment]
What I mean is, if you don't want these subprocesses to be spawned, replace `crystal app.cr` with `crystal build app.cr && ./app`, the effect will be the same, except with one less process in the list.

**Comment by jwoertink** [comment]
Ok, I guess that makes sense. It's not much different for me to use that in it's place. I'll try that out, and see how that works. Thanks! I'll go ahead and close this out if it's not really an issue.
