### ISSUE TITLE
add_header method does not exist

### ISSUE THREAD

**Issue by fridgerator** [sdogruyol/kemal#183]
The docs [here](http://kemalcr.com/docs/context/) currently reference a method `env.add_header` that doesn't seem to exist.  Perhaps that section needs to be updated?

**Comment by jwoertink** [comment]
Just to add to this, it seems that the `headers` method just works like a [hash](https://github.com/sdogruyol/kemal/blob/a8ecbde22295f4c6ce156f9d5acda304894334fb/src/kemal/middleware/http_basic_auth.cr#L29). If the kemalcr.com site has an open repo somewhere, I'd be happy to add documentation and update this.

**Comment by sdogruyol** [comment]
The site is on `gh-pages` branch. You can open a PR there
