### ISSUE TITLE
error trying to use kemal-pg

### ISSUE THREAD

**Issue by tigernassau** [sdogruyol/kemal#187]
tried to follow example but something is wrong
also wondering why json is needed if json is built into crystal 

Error in ./src/web.cr:35: undefined method 'content_type=' for HTTP::Server::Context

  env.content_type = "application/json"

require "kemal"
require "json"
require "pg"

######################################
PG_URL = "ourpass://ouruser@localhost:5432/ourdb"
DB = PG.connect PG_URL

get "/signups" do |env|
  env.content_type = "application/json"
  signups = DB.exec("select * from signups")
  release
  signups.to_hash.map do |signup|
    {email: signup["signup"] as String, full_name: signup["full_name"] as String}
  end.to_json
  render "src/views/signups.ecr"
end

######################################
Kemal.config.port = 8040
Kemal.run

**Comment by sdogruyol** [comment]
Hey there kemal-pg is DEPRECATED from now on please use [crystal-pg](https://github.com/will/crystal-pg)
