### ISSUE TITLE
Implement HTTP `HEAD` method

### ISSUE THREAD

**Issue by ilatif** [sdogruyol/kemal#19]
I' am thinking of implementing HTTP `HEAD` method to complete `kemal`'s supported HTTP methods set.

**Comment by sdogruyol** [comment]
Actually i don't know why i missed that in here https://github.com/sdogruyol/kemal/blob/master/src/kemal/dsl.cr#L1

**Comment by ilatif** [comment]
Yeah, I have explored the code and I have got a bit idea on where to make this change :-). I think it would  be nice to support `HEAD`.

**Comment by sdogruyol** [comment]
Yeah indeed :+1:

**Comment by sdogruyol** [comment]
You can implement and open a PR for it (with specs)

**Comment by ilatif** [comment]
That's great. I just checked Sinatra's `HEAD` implementation and it is returning proper response headers for every valid route even if it's type is `GET`, `POST`, `PUT` etc. Do you want `HEAD` to be implemented like this or do you want to support `HEAD` to only work with `GET` based routes?

**Comment by sdogruyol** [comment]
Actually i'm not sure which one is better

**Comment by ilatif** [comment]
I think we should support `HEAD` implementation for `GET` based routes only since it is the one most commonly used. I have seen first time in my life that `HEAD` is working for `POST` routes :-).

**Comment by sdogruyol** [comment]
Yeah i'm actually surprised to hear that it works with all routes

**Comment by sdogruyol** [comment]
Only for ```GET``` is :+1:

**Comment by ilatif** [comment]
Awesome. Thanks. :+1:.

**Comment by ilatif** [comment]
I' am thinking that we could create a static site generator from `kemal`. I' am impressed by it's speed and elegance and I hope it will be quite beneficial for developers which are always looking for better static site generators.

**Comment by sdogruyol** [comment]
Thanks for your comments. I also think that Crystal thus Kemal is pretty fast :+1:

**Comment by ilatif** [comment]
@sdogruyol: I submitted a pull request. Please see my comment which describes the steps I went through.

Thanks.

**Comment by sdogruyol** [comment]
Hey @ilatif currently i'm preparing a presentation for Crystal i'll take a look at your PR as soon as i can :+1: Thanks a lot

**Comment by ilatif** [comment]
Hi @sdogruyol, thanks for the prompt reply. Yeah sure, please take your time :-). Please share your presentation with me as well after you have presented it :-). I would love to see it :-).

Thanks.

**Comment by ilatif** [comment]
Closing this issue as this is implemented and merged.
