### ISSUE TITLE
macro didn't expand to a valid program

### ISSUE THREAD

**Issue by KingPixil** [sdogruyol/kemal#197]
I have tried using websockets and Kemal multiple times now, all I get is this error:

```
Error in ./libs/kemal/kemal/context.cr:8: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
  1.
  2.
  3.
  4.       def store = {} of String => StoreTypes
  5.         @store = {} of String => StoreTypes
  6.       end
  7.
  8.
--------------------------------------------------------------------------------
Syntax error in expanded macro: getter:4: unexpected token: =

      def store = {} of String => StoreTypes
                ^

================================================================================

    getter store = {} of String => StoreTypes
    ^~~~~~
```

Any ideas what is wrong? Thanks

**Comment by elbow-jason** [comment]
+1  - I'm having the exact same issue.

**Comment by elbow-jason** [comment]
Check your Crystal version (`crystal --version`).

I was using the `manatech/crystal` image from dockerhub. It was version 13.0. Crystal is currently on 18.2.

If you're using docker try using `FROM crystallang/crystal` for the latest version of Crystal.

**Comment by KingPixil** [comment]
I have `Crystal 0.16.0`

**Comment by sdogruyol** [comment]
@KingPixil please upgrade to Crystal `0.18.7`

**Comment by KingPixil** [comment]
@sdogruyol How? `homebrew` says I have latest

**Comment by fernandes** [comment]
@KingPixil `brew update && brew install crystal-lang` ?

**Comment by KingPixil** [comment]
Ahh, I had to update brew also, thanks :+1:

**Comment by fernandes** [comment]
@KingPixil :bow:
