### ISSUE TITLE
mathching all paths

### ISSUE THREAD

**Issue by crisward** [sdogruyol/kemal#198]
Trying to match all paths, none of the below seems to work, am I missing something in the docs?

```crystal
get "" do |ctx| 
end

get "*" do |ctx|
end

get "/*" do |ctx| 
end

```

**Comment by sdogruyol** [comment]
This is undocumented.

You can do something like

```crystal
get "/**" do |ctx| 
end
```

**Comment by f** [comment]
Also this should work I guess:

```crystal
get "/*path" do |ctx|
end
```

You also can read [radix tree algorithm](https://github.com/luislavena/radix/blob/master/src/radix/tree.cr) to understand how route matching works in Kemal.

**Comment by crisward** [comment]
Thanks for the help on this, however both of those options (and "/*") seem to match everything but the root url "/".

**Comment by sdogruyol** [comment]
Unfortunately that's a shortcoming of Radix. Closing as of now.

**Comment by samueleaton** [comment]
workaround for multiple/all routes:

```ruby
["/", "/*", "/**"].each do |route|
  get route do |env|
    "response here"
  end
end
```

Obviously this could be done with anything:

```ruby
["/", "/home", "/index"].each do |route|
  get route do |env|
    "Welcome home."
  end
end
```

**Comment by crisward** [comment]
@samueleaton thanks... 

Maybe kemal could be updated to accept an array for the route parameter...?

ie.
```crystal
get ["/","/*"] do |env|
  "Welcome home."
end
```

**Comment by samueleaton** [comment]
I've already written the code to add this feature, i can do a PR if its fine with @sdogruyol 
Although my workaround doesn't seem that difficult to do, but it would be a nice-to-have.
