### ISSUE TITLE
/room/:id websocket path not working

### ISSUE THREAD

**Issue by nwjlyons** [sdogruyol/kemal#199]
I can't match a dynamic URL using a websocket handler.

```
require "kemal"

get "/" do
  <<-INDEX
    <html>
      <body>
        <script>
        var ws = new WebSocket("ws://localhost:3000/room/123");
        </script>
      </body>
    </html>
INDEX
end

ws "/room/:id" do |socket|
  socket.send "hi"
end

Kemal.run
```

Results in a 404 response.

`WebSocket connection to 'ws://localhost:3000/room/123' failed: Error during WebSocket handshake: Unexpected response code: 404`

**Comment by sdogruyol** [comment]
@nwjlyons you can't pass named parameters to `websocket` routes. 

Please use query params instead `/room?id=123`

**Comment by nwjlyons** [comment]
Thanks. Will close.
