### ISSUE TITLE
Is It Possible to Get Multipart Form-Data?

### ISSUE THREAD

**Issue by etemelkuran** [sdogruyol/kemal#200]
Multipart form-data alabilir miyiz sağlıklı bir şekilde ve limitlere takılmadan dosyaya yazabilir miyiz?

EN:
Can we get multipart form-data and write it in file without any limitations?

**Comment by sdogruyol** [comment]
@etemelkuran actually we're waiting on this PR https://github.com/crystal-lang/crystal/pull/2967. There's no size limit whatsoever since it's using UInt64.

It's gonna be released in the next minor release of Crystal which is `0.19.1`.

**Comment by etemelkuran** [comment]
https://github.com/crystal-lang/crystal/pull/3243

I think it's ready and will be merged soon. Development of Crystal is relatively slow :sob: .

**Comment by sdogruyol** [comment]
Well, the current core development focus is the compiler. This will take a bit to get merged and then we're good to go 👍

**Comment by sdogruyol** [comment]
Closing this as waiting for the PR to be merged
