### ISSUE TITLE
Default content_type on for the default 500 error page

### ISSUE THREAD

**Issue by samueleaton** [sdogruyol/kemal#202]
If I get an error in my route somewhere after I set `env.response.content_type = "application/json"` then the 500 error page will show up as plain text. 

Would it be possible/desirable to automatically set `content_type` to `text/html` every time Kemal renders the 500 page? Seeing as it is no doubt returning HTML, it would seem more appropriate to make sure that the `content_type` matches the actual content type.

Thanks!

**Comment by jwoertink** [comment]
I would say possible, yes, desirable, no. Only because if I'm writing an API, and one of my endpoints throws a 500, I would want to get back something like `{error: "Something went wrong"}`. If it sent back HTML, then anyone using something like `JSON.parse(response.body)` would end up with some errors.

**Comment by sdogruyol** [comment]
I agree @jwoertink on this. Kemal respects the content type that you use for that route.

**Comment by samueleaton** [comment]
Sorry, i wasn't talking about custom 500 responses. Those should be set to the content type that the programmer sets them to be. I was talking about the default page that Kemal render. You obviously wouldn't want to force all 500 pages to be type html. 

**IF** the default 500 page is rendered, which is HTML, the content type should match the content, no?

**Comment by samueleaton** [comment]
Crud I just noticed in my original issue I never mentioned that I was only referring to the default 500 page. My bad.

**Comment by sdogruyol** [comment]
@samueleaton the default is HTML and as far as i know it's all the same in other frameworks. (Sinatra, Rails e.g)

**Comment by samueleaton** [comment]
I know. What I was saying is that I were to set the content type to `application/json` because I am intending to return json, but an error occurs between me setting the content type to json and me actually rendering json, and then the default 500 error page is returned as json, instead of html.
