### ISSUE TITLE
Online API documentation

### ISSUE THREAD

**Issue by aurelien-ldp** [sdogruyol/kemal#209]
Hi !

Not sure if I should create an issue for that, just tell me if not appropriated.

Would be great if the API documentation could be accessed directly online from `kemalcr.com/api` for example. The crystal website actually [does that](https://crystal-lang.org/api) (don't know how).

By "API documentation" I mean the doc generated in `/doc` by `crystal doc` or so.

It would be easier to search the documentation and facilitate contributions (I think).

Thanks

**Comment by sdogruyol** [comment]
I've just published the docs to Crystal Docs https://crystal-docs.org/sdogruyol/kemal/

I think that's a better and centralized way of sharing Crystal doc.

**Comment by aurelien-ldp** [comment]
That's perfect for me ! :)
