### ISSUE TITLE
Logger configuration

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/kemal#21]

**Comment by ilatif** [comment]
Is there any particular way to you this configuration to happen? I would like to work on this issue :-).

**Comment by sdogruyol** [comment]
I actually want this to be configurable. Either from a command line flag or from something like ```config.yml```

**Comment by ilatif** [comment]
Got it. I' am on it :smile:

**Comment by ilatif** [comment]
@sdogruyol: I checked `Logger` code and logging itself in console. I think right now we are not displaying too much information and introducing log-levels kind of thing might not look approachable. The only config I' am thinking of right now is to either completely enable/disable logger. What you think about this?

**Comment by sdogruyol** [comment]
Well i am thinking about configuring the output file. Now it logs the output to ```kemal.log``` by default and it's only in production mode

**Comment by ilatif** [comment]
Yeah. Because `Logger` is too simple at the moment, I thought of that option as well. We can give user the ability to redirect log to a file rather than STDOUT in development environment as well.

Thanks.

**Comment by f** [comment]
I think this issue kinda solved with `logging false`, right?

**Comment by sdogruyol** [comment]
Yeah @f
