### ISSUE TITLE
group or chat possible?

### ISSUE THREAD

**Issue by rdp** [sdogruyol/kemal#213]
I'd love it if there were a google group for kemal (or something, at least I didn't see one mentioned here http://kemalcr.com/), so I could ask my dumb questions like "is there a middleware DB connecting example?" etc.
Thanks!

**Comment by sdogruyol** [comment]
@rdp thanks for the issue.

We already have a gitter room (https://gitter.im/sdogruyol/kemal). I also agree that we need to have a google groups. Going to create one 👍

**Comment by rdp** [comment]
Awesome, that'll be great for old people who don't use chat like myself :)

**Comment by sdogruyol** [comment]
I've created a google group too.

https://groups.google.com/forum/#!forum/kemalcr

**Comment by rdp** [comment]
Thanks!
