### ISSUE TITLE
File Upload Not Working (For me)

### ISSUE THREAD

**Issue by etemelkuran** [sdogruyol/kemal#218]
Form input name is file.

```crystal
  post "/upload" do |env|
    parse_multipart(env) do |field, data|
      content = data if field == "file"
      File.write("test.dat", content)
    end
  end
```
Output is : #<IO::Delimited:0x1234567>
like that.

Ubuntu 16.04.1 Server x64
Am i wrong?

**Comment by sdogruyol** [comment]
Since `content` is an `IO` you need to read it till the end.

```crystal
File.write "test.data", content.gets_to_end
```
should work. But that's a really slow way of writing to files.

You better use `IO.copy` like

```crystal
File.open(file_path, "w") do |file|
    IO.copy(file, content)
 end
```

**Comment by etemelkuran** [comment]
io.copy(src,dst) so how could it be file,content

**Comment by etemelkuran** [comment]
It would be great to have an example from @rx14
