### ISSUE TITLE
Kemal as a tool

### ISSUE THREAD

**Issue by etemelkuran** [sdogruyol/kemal#219]
There can be a commandline tool for generating kemal projects and running them under src.
For example i am bored to write crystal src/app.cr , i just put a shell for it and using ./kemal or just ./k .

**Comment by f** [comment]
There's already a tool for Kemal called "fez"

**Comment by etemelkuran** [comment]
I don't like fez. I am Anti Abdulhamidist.

**Comment by alex-lairan** [comment]
@etemelkuran you are wrong ! Fez is a cool tool ! https://github.com/jwoertink/fez

**Comment by f** [comment]
Then create a tool called "fötr".

**Comment by f** [comment]
Or you can add an alias to your `~/.bashrc`.

```sh
alias fotr=fez
```

**Comment by etemelkuran** [comment]
Welcome to my comments. Coconut Jelly Man. 

I just make a k and put inside crystal src/app.cr :d 
+ MySQL adapter in Kemal's website is older one please change it with official Crystal's one.
