### ISSUE TITLE
undefined constant IO::Delimited

### ISSUE THREAD

**Issue by bkaney** [sdogruyol/kemal#232]
I did the following on OS X 10.11:

```
$ brew update
$ brew install crystal-lang
$ crystal init app hello_world
$ cd hello_world
```

Then edited `src/hello_world.cr` with the code from the like-named sample. When I try to run, I get:

```
$ crystal src/hello_world.cr
Error in ./libs/kemal/kemal/helpers/helpers.cr:85: expanding macro

  getter data : IO::Delimited
  ^~~~~~

in macro 'getter' /usr/local/Cellar/crystal-lang/0.18.7_1/src/object.cr:254, line 3:

  1.
  2.
  3.         @data : IO::Delimited
  4.
  5.         def data : IO::Delimited
  6.           @data
  7.         end
  8.
  9.
 10.

        @data : IO::Delimited
                ^~~~~~~~~~~~~

undefined constant IO::Delimited
```

**Comment by sdogruyol** [comment]
What's your `crystal -v`

**Comment by kreas** [comment]
Same issue -v is 0.18.7

**Comment by sdogruyol** [comment]
@bkaney @kreas please update to Crystal `0.19.4`.

**Comment by crisward** [comment]
I had this issue with one of my macs installing an older version of crystal from homebrew. 
Going to https://github.com/crystal-lang/crystal/releases and unzipping and manually copying the binary fixed it.

**Comment by bkaney** [comment]
Yea, I'll try upgrading Crystal manually, same issue with homebrew for me.
