### ISSUE TITLE
Proposal: Rename the return_with macro to respond_with or respond

### ISSUE THREAD

**Issue by samueleaton** [sdogruyol/kemal#235]
`respond_with` seems like more appropriate verbiage for an HTTP server. `return_with` seemed a little off to me when I first learned about it.

Another option would be to shorten it even more and just use the word `respond` and drop the `_with`—something not possible with `return_with` for an obvious reasons.

**Comment by samueleaton** [comment]
@sdogruyol What did you think about this? There are some additions I want to add in this area after this is resolved. 🙂

**Comment by sdogruyol** [comment]
@f @askn WDYT about this?

**Comment by sdogruyol** [comment]
@samueleaton actually neither `return_with` nor `respond` reflects the intention of this action.

I think it should be `halt`. An example like below makes more sense

```crystal
get "/" do |env|
  if some_condition
    halt env, 401
  end
  "Successful"
end
```

**Comment by sdogruyol** [comment]
Close via https://github.com/sdogruyol/kemal/commit/d676b559d2ed1486545dbdf061c5a0fa6e69c082
