### ISSUE TITLE
Error handling with custom middleware handler

### ISSUE THREAD

**Issue by jwoertink** [sdogruyol/kemal#240]
I have a custom handler doing:

```crystal
require "kemal"
class AuthorizationHandler < HTTP::Handler        
  ACCEPT = "application/vnd.api.v1+json"

  def call(env)
    if env.request.headers["Accept"] != ACCEPT
      env.response.status_code = 401
    end
    call_next(env)
  end
end

Kemal.config.add_handler(AuthorizationHandler.new)
error 401 do
  {"error" => "Unauthorized"}.to_json
end

get "/" { Member.all }
Kemal.run
```

If I visit localhost:3000 in the browser, this should return the error json since the Accept header is going to be `	
text/html,application/xhtml+xml`, but that's not what I get.

![screen shot 2016-10-31 at 3 59 50 pm](https://cloud.githubusercontent.com/assets/2391/19874672/312c2d82-9f84-11e6-85b9-44febcc08d84.png)

As you can see from the screenshot, it set the 401 properly, but it still returned my data. The `error` blocks should do some sort of halt on the middleware chain

**Comment by sdogruyol** [comment]
Actually this works but if you're writing to `env` yourself with `env.response.print` it won't.

Since you're using a middleware for authentication you can just return to `halt`.

```crystal
require "kemal"
class AuthorizationHandler < HTTP::Handler        
  ACCEPT = "application/vnd.api.v1+json"

  def call(env)
    if env.request.headers["Accept"] != ACCEPT
      env.response.status_code = 401
      return env.response
    end
    call_next(env)
  end
end
```

**Comment by sdogruyol** [comment]
Also an `error` block is for customizing the response not actually for `halt`ing

**Comment by jwoertink** [comment]
I thought if the `env.response.status_code` is changed, then kemal will automatically run the error block it matches. If I do `return env.response` I just get back an empty response. I've changed the route to just be `{"a" => 1}.to_json` so no `print` is being called. 

```crystal
require "kemal"
class AuthorizationHandler < HTTP::Handler        
  ACCEPT = "application/vnd.api.v1+json"

  def call(env)
    if env.request.headers["Accept"] != ACCEPT
      env.response.status_code = 401
      return env.response
    end
    call_next(env)
  end
end

Kemal.config.add_handler(AuthorizationHandler.new)
error 401 do
  {"error" => "Unauthorized"}.to_json
end

get "/" { {"a" => 1}.to_json }
Kemal.run
```

**Comment by sdogruyol** [comment]
@jwoertink it will return what you build at the middleware without reaching the route which is

```crystal
env.response.status_code = 401
return env.response
```

This will render empty response.

**Comment by jwoertink** [comment]
Looks like tracking from Master branch fixed this issue. Thanks!
