### ISSUE TITLE
Instead of passing `Kemal::context.new` as `env` in route's callback, we should have something like Express.js

### ISSUE THREAD

**Issue by ilatif** [sdogruyol/kemal#25]
Crystal is quite a fun programming language to work with. I have been trying to remove `env.redirect` etc. to simplify method calls to something like `redirect`. I actually want to do this because in my opinion when `kemal` has support for templates having template getting rendered as `env.render` is not going to look cool.

Due to some core differences in Ruby and Crystal I' am unable to achieve this so far because there is no `self` in Crystal inside blocks which makes sense but this also means that we cannot apart `env` from method calls inside defined routes' callback.

However, there is a simple solution. Instead of passing something like `env`, we should pass something like `req` and `res`. For example,

```ruby
  get "/" do |req, res|
    # important stuff here
  end
````

This will make method invocations more expressive and we can call appropriate methods on proper objects. For example to access `params` we can call `req.params` and to redirect we can call `res.redirect` and to render we can do `res.render`.

This is what Express.js is doing and I think it's quite elegant.

**Comment by sdogruyol** [comment]
What do you mean?

**Comment by ilatif** [comment]
I have updated the comment, please check.

**Comment by sdogruyol** [comment]
I think instead of yielding ```res```and ```res``` we better find a way to use this function like ```render``or ```redirect```

**Comment by ilatif** [comment]
I have tried with my limited Crystal's knowledge but I think that is not possible without having some tricks/hacks involved. Ruby is quite eloquent in the sense that we can easily alter `self` before `block` invocation, but Crystal is a whole different story.

Having `req` and `res` in block params are quite expressive in my opinion.

**Comment by ilatif** [comment]
Let's get opinion from other contributors as well. Since I don't know anyone of them, it would be nice if you mention them here :-).

**Comment by sdogruyol** [comment]
I think @asterite is the most capable here :+1:

**Comment by ilatif** [comment]
Great. I have also tried by passing routes' block in other function as block argument and call them with `with context yield`, but I' am getting some serious compile-time errors :-).

**Comment by ilatif** [comment]
@sdogruyol: I read comments from this issue and tried `with context yield` by reading from here. Please check https://github.com/manastech/crystal/issues/1095 for more details about not having `self` in blocks/procs.

**Comment by ilatif** [comment]
@sdogruyol: Also I think it's not a good idea to call some methods or accessing variables with `env` and call some methods without any receiver. Either we access everything in route's callback with `env`or we should ignore it altogether for consistency purposes.In Sinatra, there is no need to define explicit receiver in route's callback.

I think keeping in mind Crystal's limitations we should either use `env` for all method invocations like `env.redirect`, `env.render` etc. or we could also use `req`, `res` by taking inspiration from Express.js

**Comment by sdogruyol** [comment]
I think we should keep the spirit of Sinatra as much as possible :+1:

**Comment by ilatif** [comment]
:-). So we should try to be able to handle `redirect`, `render`, `params` etc. without any explicit receivers?

**Comment by sdogruyol** [comment]
Well that should our goal :) If we can't then we can use ```env``` for it WDYT?

**Comment by ilatif** [comment]
As far as I have tried I think it's not possible :-). But there is another thing we can do :stuck_out_tongue:. Instead of calling `Kemal::Context`'s instance as `env` in defined routes' block, we can call it `app` :smile:. `app.render`, `app.redirect` feel much better than `env.render` and `render.redirect`. What you think about this?

**Comment by sdogruyol** [comment]
Well it's just renaming the yielding variable :smile: But it makes sense :+1:

**Comment by ilatif** [comment]
Yeah, that's exactly what I mean. And developers always tend to use parameters in blocks which are suggested in documentation. So I think we are good with `app` than `env`. If you are fine with this than I will submit a Pull Request tomorrow by changing `env` to `app` in all places :smile:.

**Comment by sdogruyol** [comment]
Yeah i'm okay with this :+1:

**Comment by ilatif** [comment]
Great. I will submit a pull request tomorrow.

BTW, what are the next features you have in mind for `kemal`? Since today, I have been exploring codebase and trying to fix things which I found missing or thought can be improved. But I would like to hear what's your take on new features.

P.S. `kemal` in Turkish is exactly equal to what we have in Urdu :smile:. You have done `kemal` would be correct if I' am not wrong :smile:.

**Comment by sdogruyol** [comment]
Actually the most important missing feature is ```render```. Currently we cant render a view with dynamic params. ```ecr``` is OK for template

**Comment by sdogruyol** [comment]
Meanwhile ```Kemal```meaning is the same :)

**Comment by ilatif** [comment]
Awesome :smile:. `ecr` seems perfect choice for `kemal`. I will explore and see how could we integrate it.

I think that's not the correct place for this thing but I really like Turkey specially Istanbul and been trying to learn Turkish language but I found it really hard despite of huge similarities Turkish language have with Urdu :smile:.

**Comment by sdogruyol** [comment]
I've created a gitter room for Kemal https://gitter.im/sdogruyol/kemal

**Comment by ilatif** [comment]
Cool :+1:. Just joined :smile:.

**Comment by sdogruyol** [comment]
I'm closing this for now.
