### ISSUE TITLE
Size of index.html on page

### ISSUE THREAD

**Issue by fffuture** [sdogruyol/kemal#250]
Hello. I try to serve index.html as file and after rendering I see size of file in bytes.

my code:
```
  get "/" do |env|
    send_file env, "public/index.html", "text/html"
  end
```

and following index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      1
    </div>
  </body>
</html>
``` 
After rendering I have:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      1
    </div>
  </body>
</html>
154
```
154 it is size of file (I see in Network tab in Firebug).
Whats wrong? Thanks.

**Comment by sdogruyol** [comment]
May i ask you what's the purpose of this? Are you doing this for rendering the page?

**Comment by fffuture** [comment]
I want to send index.html when user GET '/' route, and after use angular or react or something else

**Comment by sdogruyol** [comment]
So why don't you use `render` and then use whatever you want on front end. 

More Info on views 
http://kemalcr.com/docs/views/

**Comment by fffuture** [comment]
ok. I did it, but then I need to reload project every time when I make changes in layout. If I will generate layout through JSX, it not a problem, but It not very comfortably.
Also maybe you advice to me something like nodemon or gulp-watch for crystal

**Comment by samueleaton** [comment]
@fffuture There is something i wrote like nodemon called [sentry](https://github.com/samueleaton/sentry)
