### ISSUE TITLE
Running kemal doesn't bind to 0.0.0.0 ?

### ISSUE THREAD

**Issue by Vikaton** [sdogruyol/kemal#28]
I run the command `./server -p 80 -e production`and it says im running on http://0.0.0.0:80, but when I try to access my website from the browser (stackin.money) it says Connection refused. I cURLed from my terminal to http://0.0.0.0:80 and it worked, but cURLing to http://stackin.money again shows connection refused. I tried sinatra and did `ruby y.rb -p 80 -o 0.0.0.0` and I accessing my website through http://stackin.money worked, any fix to this?

**Comment by sdogruyol** [comment]
I think this is related to http server. Going to take a look at it!

**Comment by Vikaton** [comment]
Okay thanks!

**Comment by sdogruyol** [comment]
This is now fixed at ```master```

**Comment by Vikaton** [comment]
still getting "Connection Refused" :(

**Comment by Vikaton** [comment]
Or maybe it does work, my shards said it updated the kemal git but it says it's using Using kemal (aa0d97aa42898bbae8b86992ebad2f34a94b37f5) which isnt the latest commit.

**Comment by sdogruyol** [comment]
You need to do shards update to get the latest
