### ISSUE TITLE
Kemal is not thread-safe because HTTP::Server#listen isn't threadsafe

### ISSUE THREAD

**Issue by ilatif** [sdogruyol/kemal#30]
I have been trying hard to remove env. And while doing that I found out that Kemal is not thread-safe .
Because HTTP::Server is not thread-safe by-default.
I have found a way to make it thread-safe by using most established technique i.e. creating a process for each incoming request.
This will not only make Kemal thread-safe which will be beneficial for us in future, but it will allow us to assign context as global variable and we can use that global variable everywhere like redirect, render.
We can also expose params as a method and this will completely eliminate need of having env.params.

I discovered this thread-safety issue while creating a global variable in requests. I was putting some sleep in requests as well to notice the behaviour of that global variable. And to my expectation, it did what I was anticipating. I stored content-type as text/plain for one of the requests in a global variable but due to sharing of global variable among all requests, it was being applied to all requests.
I tried the exact same thing with new forked-based server implementation and that issue vanished .
Please let me know what you think about this?

**Comment by ilatif** [comment]
Example:

```ruby
get "/one" do |env|
  $content_type = "text/html"
  sleep(5)
  env.content_type = "#{$content_type}"
  "<strong>Hello World from One</strong>"
end

get "/two" do |env|
  $content_type = "text/plain"
  sleep(2)
  env.content_type = "#{$content_type}"
  "<strong>Hello World from Two</strong>"
end
```

The response one should expect is to have html return from `/one` being rendered as html while html returned from `/two` being rendered as plain-text. But because of non thread-safe behaviour, both responses are rendered as plain-text. Global variable has been deliberately used to indicate a resource whose data might get corrupt due to non thread-safety.

This thing will get fix if we go with fork-based model. Remember, Sinatra is thread-safe by-default because if uses `Rack::Lock` middleware.

**Comment by sdogruyol** [comment]
This is also related to ```HTTP::Server``` and soon or later it'll become threadsafe. WDYT about this @asterite

**Comment by ilatif** [comment]
But for Kemal, we can fix this easily. I have fixed this and would like to show you :-).

**Comment by ilatif** [comment]
We don't know whether Crystal decided to fix thread-safety issue and even then they does, we don't know how long will it take. When `HTTP::Server` became thread-safe we can definitely use their implementation, but since then I think we can go with our implementation that will make Kemal thread-safe.

**Comment by sdogruyol** [comment]
Could you please open a ```PR``` for this

**Comment by ilatif** [comment]
Yeah sure. I will do this in few hours :+1:. Do you want to have specs as well. I just inherited from `HTTP::Server` and created a new method that is handling forking stuff. Since, `HTTP::Server` is very well tested, I think we shouldn't write specs. Thoughts?

**Comment by sdogruyol** [comment]
A few specs would be nice if you can explicitly test the forking ability

**Comment by ilatif** [comment]
I will write spec(s) that will make sure that even though multiple requests are accessing same global variable, both end-up in maintaing state as per their route's callback. What you think about this?

**Comment by sdogruyol** [comment]
Sounds OK

**Comment by ilatif** [comment]
Thanks :+1:.

**Comment by waterlink** [comment]
This is not a thread-safety problem of Crystal, or `HTTP::Server`. That is
a concurrent-safety problem of the code. If you create a global shared
state you will have concurrency problems. Period.

If you want to not have concurrent problems, you should either avoid shared
state or use shared data access patterns (such as: mutex, transactional
memory, etc.).

In this case, each request can execute in its own `Fiber` and each of these
will have its own `env` available to it.



--
Best Regards,
Oleksii Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

**Comment by sdogruyol** [comment]
I agree with @waterlink on this.

**Comment by ilatif** [comment]
Even though there are guidelines on not to create global variables, class variables to make code thread-safe, one way or another developers end-up doing that knowingly or unknowingly. Every major framework be it Rails, Sinatra make sure at the basic level that no two threads run at the same time. They can implement thread-safety at some outstanding level, but still they provide primitives that will make sure that no two threads run at a same time.

I' am not abusing or undermining `HTTP::Server` or `Kemal` in any way. All I' am saying is, if we can make something thread-safe we should. All I' am doing is that for every incoming request I have created a process, I don't think that's a bad thing to do to achieve thread-safety :-).

**Comment by waterlink** [comment]
@ilatif My point here is that doing process/per/request scheme is very ruby-ish, in my opinion, it really goes away from light-weigh and fast :)

In this case, I would rather try to leverage concurrency tools that `crystal` itself gives you (`Fiber`s and channels). That way I would be able to handle a lot of requests with one thread (very low memory foot-print). Only the next step is to scale in direction of having multiple threads/processes. Maybe something like cluster logic even.

If you are aware of users of your framework to potentially create global state that is not thread-safe, give them and document well the feature that will allow them to do that in a thread-safe way almost without any effort.

**Comment by ilatif** [comment]
@waterlink Thanks for your reply. Basically, forking a process per request is not ruby-ish, it's actually apache-ish :stuck_out_tongue:.

I totally agree with you that we should do some serious implementation using Fibers/Channels to achieve an ideal concurrency level. But in my opinion, since Kemal is not mature enough, we shouldn't implement such things now.

Also, no matter, how well you document not creating global variables/shared data-structures etc., developers end-up doing that knowingly or unknowingly. If they are not writing such code, maybe some library on which their code is dependent creates some global variables. Ruby is quite mature and so is the Rails. But you know that even to this day Rails cannot 100% guarantee thread-safety. In order to be thread-safe you either have to block all other threads while current one is processing or you have to create separate processes for each of them.

**Comment by waterlink** [comment]
> Also, no matter, how well you document not creating global variables/shared data-structures etc., developers end-up doing that knowingly or unknowingly.

I was thinking about documenting how they should define such global state in a concurrent-safe way, instead of telling them not to do it at all.

**Comment by ilatif** [comment]
I' am not saying that I' am going to stop them from using global variables :-). If we go with forked-based model these issues will be fixed automatically :-).

**Comment by asterite** [comment]
My thoughts are exactly those of @waterlink.

**Comment by sdogruyol** [comment]
Thanks @asterite . Would mind telling why `listen_fork` is going to be removed from `HTTP::Server`

**Comment by ilatif** [comment]
@asterite: You are right and I completely agree with @waterlink's comments as well. But the point I was trying to raise is related to make Kemal thread-safe by-default just like Rails does. Even though, Ruby has a GIL, Rails/Sinatra still makes sure that no other thread runs while current one is running. Do you think it's not good to fork a new process for each incoming request?

**Comment by waterlink** [comment]
I wonder what happens to the server if you bash it with couple of hundreds
of thousands of requests per second or something like that. I think
everything would crash, because forking the process is too expensive in
terms of time and memory.

Ruby/Rails solution that use forked model, usually have multiple workers (=
number of cores * 2, usually) pre-forked on server start and they just
serve one request at a time. Plus, there is master server that accepts and
sends client connections to these workers, when they finish their
respective requests.


--
Best Regards,
Oleksii Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

**Comment by ilatif** [comment]
@waterlink: Thanks for your reply :-). I totally agree with you but since Kemal is not a heavy framework like Rails is, requests will not take much time from start to finish. So forking new processes is not time consuming in my point of view. But I still do agree that forking is quite a basic thing and to build a framework which could scale well, this forking thing can create problems.

But I insist that we should at-least have Mutex locking kind of thing within requests just like `Rack::Lock` does in-order to make Kemal thread-safe.

**Comment by waterlink** [comment]
Actually `Mutex` sounds pretty good. And it should be easy to disable, like `Kemal.threadsafe` (or maybe `Kemal.fibersafe`, because technically in Crystal you use `Fiber`s, not `Thread`s).

:+1:

**Comment by waterlink** [comment]
Then as a next step, you can add a forking web-server on top of the `kemal`, maybe even as a separate library. And provide it as a default dependency.

**Comment by sdogruyol** [comment]
@waterlink nice!

**Comment by ilatif** [comment]
Yup. Having Mutex makes it pretty close to what `Rack::Lock` does. I really liked your idea of creating a stand-alone library for giving forking ability to web-frameworks built in Crystal :-).

**Comment by lbguilherme** [comment]
Please don't trade performance for imposed safety.

When I, as a user, create a global variable I do expect it to be shared between all handlers directly and changing it should affect other ongoing requests unless I want to prevent so. Think about a counter, o some kind of real time server that doesn't rely on a database to store data but do it via a global state. Fibers should be treated just like threads for the end users (they will run parallelly some day), and the user should be responsible for keeping it in sync. 

> I totally agree with you but since Kemal is not a heavy framework like Rails is, requests will not take much time from start to finish. 

I think Kemal is too low level to make such an assumption. Imagine a REST API that implement some long pulling. A single request can last for minutes and I do not want the server to be blocked during it. 

Blocking on each request can be a good feature to some, but I believe this should be a opt-in, not a default. Compare the Apache way with the Nginx way.

**Comment by sdogruyol** [comment]
Closing this for now.

**Comment by rdp** [comment]
maybe crystal could have an option for "process one request at a time"
