### ISSUE TITLE
Problem with static files

### ISSUE THREAD

**Issue by airled** [sdogruyol/kemal#33]
I have a problem with css. In the app directory I have `public/styles.css`, `views/index.ecr` and `src/app.cr`
`app.cr` looks like
```
require "kemal"

module App::Crystal
  get "/" do
    render "views/index.ecr"
  end
end
 ```

`index.ecr` has link-tag `<link rel="stylesheet" href="/styles.css">`
When open `localhost:3000` html renders well but css request has 404. Trying different pathes in `link` like `public/styles.css`, `/public/styles.css`, `styles.css`, `/styles.css` doesn't work.

**Comment by sdogruyol** [comment]
Hey there, currently `StaticFileHandler` is not working as intended. I'll fix this ASAP

**Comment by sdogruyol** [comment]
Meanwhile you can do something like below

https://github.com/f/kamber/blob/master/src/kamber.cr#L31-L34

**Comment by ilatif** [comment]
@sdogruyol: I' am also looking into it and will do my best to submit a patch asap :-).

**Comment by airled** [comment]
Got it. Thank you.

**Comment by sdogruyol** [comment]
You can now use `public/main.css` which should be placed under `public` folder

**Comment by airled** [comment]
Here we go. Thanks.
