### ISSUE TITLE
How about having javascript_include_tag, stylesheet_link_tag or similar in Kemal?

### ISSUE THREAD

**Issue by ilatif** [sdogruyol/kemal#34]

**Comment by sdogruyol** [comment]
Yeah that's pretty easy to do with macros :)

**Comment by ilatif** [comment]
Yeah. I was looking for suggestions that whether we should have them? Also I will insist on using methods instead of macros so that users can pass variables as well or string interpolated urls etc.? :-)

**Comment by ilatif** [comment]
@sdogruyol: If you think that we shouldn't have this in Kemal then please let me know and I will close the issue :-). If you think we can have this kind of thing but with more compact names then I would love to work on this :-).

**Comment by sdogruyol** [comment]
Yeah. I'd really like `Kemal` to be as simple as possible thus closing the issue :+1:
