### ISSUE TITLE
Handling multipart/form-data

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/kemal#40]
This is actually needed for file uploads and multipart forms.

Currently we don't have any multipart form parsers for Crystal. Thinking of writing this as a seperate `shard` and then making a plugin for `Kemal`.

**Comment by 007lva** [comment]
:+1:

**Comment by ozziest** [comment]
:+1:

**Comment by f** [comment]
Parsing multipart/form-data is kind of hell to implement with state-machine. Too many cases to handle, doesn't seem easy to me.

Someone should bind `libmultipartparser`.

**Comment by nwmcsween** [comment]
I'll give this a shot soon, multipart seems pretty simple as it seems to just be a simple state machine, w/ C you could use computed goto's but that's probably overkill for something like this.

**Comment by sdogruyol** [comment]
@nwmcsween any update on this?

**Comment by sdogruyol** [comment]
Waiting on https://github.com/crystal-lang/crystal/pull/2967 to get merged to upstream.

**Comment by f** [comment]
Excited to see this on Kemal soon!

**Comment by sdogruyol** [comment]
Finally https://github.com/sdogruyol/kemal/pull/216
