### ISSUE TITLE
Include wrk command

### ISSUE THREAD

**Issue by kbrock** [sdogruyol/kemal#43]
Hello,

Could you include the `wrk` command you used in the `README.md` or an `example/wrk.sh` or something?

It is always great to see what people are running to load test a framework, and use that same command to load test other frameworks as well and/or validate the claims.

This framework looks great. Thanks for putting this together.

**Comment by sdogruyol** [comment]
Hey @kbrock 

Thanks for your kind words. I'll make a gist for that like i did for Websocket benchmark https://gist.github.com/sdogruyol/bdd400a6eac13e26228e 

Is that OK for you?

**Comment by sdogruyol** [comment]
Here's the gist: https://gist.github.com/sdogruyol/34ffe2f60acfeba9b095

**Comment by kbrock** [comment]
@sdogruyol this is great thanks
