### ISSUE TITLE
It doesn't support Crystal 0.9.1

### ISSUE THREAD

**Issue by JCarlesVilaseca** [sdogruyol/kemal#46]
./libs/kemal/kemal/context.cr:26: undefined local variable or method 'status_code'

  delegate status_code, :"status_code=", :"content_type=", @response
           ^~~~~~~~~~~

**Comment by sdogruyol** [comment]
Hey @JCarlesVilaseca 

- Kemal v0.4.0 supports Crystal 0.9.1
- Kemal 0.5.0 and 0.6.0 supports Crystal 0.10.0.
- Kemal master supports Crystal latest release.

I'm gonna update the README perse.
