### ISSUE TITLE
Handling http request type

### ISSUE THREAD

**Issue by hamitturkukaya** [sdogruyol/kemal#51]
Hello;

I want to seperate my logic according to http request type(GET, POST, PUT etc.). But i couldn't make it.
for example,

```ruby
get "/" do |env|
  "GET REQUEST"
end

post "/" do |env|
  "POST REQUEST"
end
```

response is always "GET REQUEST"
also when i try to run only

```ruby
post "/" do |env|
  "POST REQUEST"
end
```

i can get same response with GET or PUT request.

**Comment by sdogruyol** [comment]
Are you using Kemal `0.6.0` or tracking `master`? If the latter then it's not yet implemented since the router is being rewritten from scratch

**Comment by sdogruyol** [comment]
Fixed on https://github.com/sdogruyol/kemal/commit/b37dd29d4b244721b459ac4d420b9b5a88fdf1f6
