### ISSUE TITLE
undefined local variable or method 'status_code'

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [sdogruyol/kemal#56]
Error in ./libs/kemal/kemal/context.cr:30: undefined local variable or method 'status_code'

I am getting this error. Any idea why?

**Comment by sdogruyol** [comment]
Could you please your Crystal and Kemal version

**Comment by stephan-nordnes-eriksen** [comment]
never mind, I did not update brew before installing the newest crystal. Sorry.
