### ISSUE TITLE
Should be error when TCP port is busy

### ISSUE THREAD

**Issue by SergXIIIth** [sdogruyol/kemal#57]
Hello,

would nice to have an error when TCP 3000 is busy. Currently I had

```
$ crystal run src/chat.cr 
[development] Kemal is ready to lead at http://0.0.0.0:3000

msa@Mag2 ~/prj/vid/app/chat (master)
$ 
```

**Comment by f** [comment]
This may be useful in `kemal.cr`:

```crystal
if `lsof -i :#{config.port} | grep LISTEN | wc -l`.chomp.to_i > 0
    puts "Port #{config} is in use!"
    exit 1
end
```

**Comment by fatih** [comment]
I assume this is using `http.Listen` from the `http/server` package. That method uses the `TCPServer` [under the hood](https://github.com/manastech/crystal/blob/master/src/http/server/server.cr#L126), and it already [raises an error if the port is bind](https://github.com/manastech/crystal/blob/master/src/socket/tcp_server.cr#L11).  

I don't know how errors are being handled (exceptions?) but this could be leveraged to show the error to the user.

**Comment by sdogruyol** [comment]
@fatih definitely! 

We've done this with @askn but not implement this into `Kemal` yet. And yes you handle errors with `exception`s.

**Comment by sdogruyol** [comment]
This is now fixed with https://github.com/sdogruyol/kemal/commit/fd904cd98d8dff92752b3484f6d7714477ddc6dd
