### ISSUE TITLE
Bugs with the refactoring of http std lib in crystal 0.11.0.

### ISSUE THREAD

**Issue by raydf** [sdogruyol/kemal#59]
There's a lot of bugs related to the new context object in the http server refactoring for crystal 0.11.0.
```
Error in ./libs/kemal/kemal.cr:35: instantiating 'HTTP::Server#listen()'

  server.listen
         ^~~~~~

in macro 'spawn' /opt/crystal/src/concurrent/concurrent.cr:37, line 8:

  1.   
  2.     ->(
  3.       
  4.         __arg0 : typeof(server.accept),
  5.       
  6.       ) {
  7.       spawn do
  8.         handle_client(
  9.           
 10.             __arg0,
 11.           
 12.         )
 13.       end
 14.     }.call(server.accept)
 15.   

        handle_client(
        ^~~~~~~~~~~~~

instantiating 'handle_client(TCPSocket+)'
in /opt/crystal/src/http/server/server.cr:157: instantiating 'HTTP::Handler+#call(HTTP::Server::Context)'

        @handler.call(context)
                 ^~~~

in ./libs/kemal/kemal/middleware/http_basic_auth.cr:20: undefined method 'headers' for HTTP::Server::Context

      if request.headers[AUTH]?
                 ^~~~~~~

================================================================================

HTTP::Server::Context trace:

  ./libs/kemal/kemal/middleware/http_basic_auth.cr:19

        def call(request)
```

**Comment by sdogruyol** [comment]
@raydf i will make a release soon with support for 0.11.0

**Comment by raydf** [comment]
Thanks @sdogruyol, just documenting the changes for anyone new to crystal having trouble with kemal.

**Comment by sdogruyol** [comment]
Thanks a lot!

**Comment by f** [comment]
`HTTP::Response` is now `HTTP::Client::Response` / `HTTP::Server::Response` which causes errors. I made some changes to make it work but couldn achieved a full success. But it doesn't seem too hard to migrate to 0.11.x

**Comment by sdogruyol** [comment]
@f i'm currently migrating to 0.11.0. And it's a total rewrite :+1:

**Comment by sdogruyol** [comment]
@raydf you can track master for Crystal 0.11.0 

The support is added in https://github.com/sdogruyol/kemal/commit/72a3bec2aa7da5dd56fd905bc93b43e36895c4ca but still missing `view` macros because of https://github.com/manastech/crystal/pull/2053

**Comment by f** [comment]
We've solved the problem. I think it's now on master.

**Comment by sdogruyol** [comment]
Kemal master now support Crystal 0.11.0 :+1:

**Comment by raydf** [comment]
Thanks, @f and @sdogruyol . I'll update the shards in my projects. Again, excellent work.
