### ISSUE TITLE
Dismantle Radix from Beryl

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/kemal#62]
I want to implement Radix without Beryl in the upcoming Kemal release.

//cc @luislavena , @f

**Comment by sdogruyol** [comment]
I've replace Beryl with https://github.com/f/radix

WDYT @luislavena ?

**Comment by luislavena** [comment]
Thought from my last comment on previous issue that I would work on the
extraction this weekend (there are a few hours left on this timezone).
Didn't know there was such a rush to get it sorted out.

Code is MIT so I guess is OK, but I would have prefer do it myself under my
account.

Sorry for top posting, sent from mobile.

**Comment by sdogruyol** [comment]
It's OK. Actually i'm not making a release today :+1:

**Comment by luislavena** [comment]
@sdogruyol clean version of Radix extracted from Beryl here:

https://github.com/luislavena/radix

@f the repo mentioned above incldues the files directly without fork from Beryl and the noise of the removal of all Beryl related files.

Cheers.

**Comment by f** [comment]
@luislavena Thank you :) I already opened a PR: https://github.com/sdogruyol/kemal/pull/64

**Comment by sdogruyol** [comment]
Thanks @luislavena @f  :heart_eyes:
