### ISSUE TITLE
post method return 404

### ISSUE THREAD

**Issue by kostya** [sdogruyol/kemal#67]
```
require "kemal"
get "/a" do
  "a"
end

post "/b" do
  "b"
end
```

```
curl http://localhost:3000/a
curl http://localhost:3000/b -X POST -d '{"bla":12}'
```

```
2016-01-25 22:45:33 +0300 | 200 | GET /a - 91µs
2016-01-25 22:47:08 +0300 | 404 | POST /b - 65µs
```

**Comment by sdogruyol** [comment]
Ouch! This is definitely a bug. Seems like we need to improve the router @f

**Comment by sdogruyol** [comment]
This is not related to `POST` but more like the router gets the first match on the routes that are exact size.

**Comment by f** [comment]
Hmm, actually Radix creates a path "method path" pattern. And the tree path is like "POST /b" for radix. @sdogruyol Can you try `radix_path` to generate "post/b"? I am not on computer, cannot try right now.

**Comment by sdogruyol** [comment]
@f it's `POST /b`

**Comment by f** [comment]
@kostya PR https://github.com/sdogruyol/kemal/pull/68/files fixes this issue. Can you verify @sdogruyol?

**Comment by sdogruyol** [comment]
Fixed as of https://github.com/sdogruyol/kemal/commit/23b09ff645aee949ab3c1298a5726783b2d4984b
