### ISSUE TITLE
Error page doesn't (re)set content_type

### ISSUE THREAD

**Issue by robacarp** [sdogruyol/kemal#674]
### Description

I'm building a small json/rest API. One part of rest is to respond appropriately via status code when an object is not found, and also render a response body.

I tried this code:

```crystal
get "/job_run/:id" do |env|
  env.response.content_type = "application/json"

  job_id = env.params.url["id"]
  job = Mosquito::Api::JobRun.new job_id

  if job.found?
    job.to_json
  else
    env.response.status = HTTP::Status::NOT_FOUND 
    {
      error: "Job not found",
      see_other: "/job_runs"
    }.to_json
  end
end
``` 

But it doesn't render my JSON, it renders the error page. 

I believe I can register an error handler for 404s, but that doesn't really do what I want. I don't want a _global_ not-found message, I want to be able to provide actionable advice to an API user on an endpoint specific basis. Moreover, I don't see any way in the documentation to render an error page with a content type of JSON.

I think it might make sense to distinguish between 404 errors which are generated by the application and "invalid route errors" which are generated by the framework not knowing how to route a request.

However, at a minimum, it should be considered a bug that when the error page is rendered, Kemal doesn't set the content type appropriately.

### Versions

Kemal 1.4

**Comment by aravindavk** [comment]
As a workaround, you can use `halt`. 

```crystal
get "/job_run/:id" do |env|
  env.response.content_type = "application/json"

  job_id = env.params.url["id"]
  job = Mosquito::Api::JobRun.new job_id

  if job.found?
    job.to_json
  else
    err = {
      error: "Job not found",
      see_other: "/job_runs"
    }.to_json

    halt env, status_code: 404, response: err
  end
end
```
