### ISSUE TITLE
Unable to add handlers at a specific position in the stack

### ISSUE THREAD

**Issue by robacarp** [sdogruyol/kemal#689]
### Description

I've added [Honeybadger](https://github.com/honeybadger-io/honeybadger-crystal/) to my kemal app, and Honeybadger started catching 404 errors. I don't consider 404s something worth of an error notification, so I also added a custom error handler which renders a page -- but honeybadger still gets the ping on a 404!

I've traced the problem to the ordering of Handlers within Kemal.config:

```
Kemal::InitHandler
Kemal::LogHandler
Kemal::HeadRequestHandler
Kemal::ExceptionHandler
Kemal::StaticFileHandler
Honeybadger::Handler
Kemal::WebSocketHandler
Kemal::RouteHandler
```

The HTTP request progresses through the middleware from top to bottom, and then back up from bottom to top. What's happening is that when I added the custom handler for honeybadger, it's placed too low in the stack. The exception for RouteNotFound is generated in RouteHandler, seen by Honeybadger::Handler, and then rescued in Kemal::ExceptionHandler.

### Steps to Reproduce

This minimal example reproduces the problem:

```crystal
require "kemal"
require "honeybadger"

Honeybadger.configure do |config|
  config.api_key = ENV.fetch("HONEYBADGER_API_KEY") { "" }
  config.environment = Kemal.config.env
end

add_handler Honeybadger::Handler.new

error 404 do |env|
  "not found page"
end

Kemal.run
```

Visiting any route triggers the behavior:

```
2024-09-15 13:05:06 UTC 404 GET /foo 145.71µs
2024-09-15T13:05:06.775996Z   INFO - honeybadger: Success ⚡ Development mode is enabled; this error will be reported if it occurs after you deploy your app.
```

**Expected behavior:** 

I would like to be able to configure the handler position with `add_handler`.

### Versions

Kemal 1.5.0

**Comment by sdogruyol** [comment]
Thanks for the report @robacarp, we actually have `add_handler` with custom index support. Guess the documentation needs to be updated

```crystal
# This adds MyCustomHandler instance to 1 position.
# Be aware that the index starts from 0.
add_handler MyCustomHandler.new, 1
```
