### ISSUE TITLE
Measured performance is not so fast

### ISSUE THREAD

**Issue by genki** [sdogruyol/kemal#73]
I have measured performance by `ab` command.
Here is the code.

```crystal
require "kemal"

get "/" do
  "test"
end
```

```shell
$ crystal build --release server.cr
$ ./server -e production &
$ ab -n 10000 -c 100 http://localhost:3000
...
Requests per second:    1144.30 [#/sec] (mean)
Time per request:       87.390 [ms] (mean)
Time per request:       0.874 [ms] (mean, across all concurrent requests)
Transfer rate:          74.87 [Kbytes/sec] received
...
```

Using macbook pro (CPU: 3.1 GHz Intel Core i7, MEMORY: 16 GB 1867 MHz DDR3)

The result is about 100 times slower than expected.
Are there missing configuration options?

**Comment by sdogruyol** [comment]
Hey @genki 
Thanks for the interest, actually i don't use `ab` in OS X. Because it's buggy.

Could you please rerun the benchmark with `wrk`

```
wrk -c 100 -d 20 http://localhost:3000
```

**Comment by genki** [comment]
Using wrk, I got a good result as follows

```
$ wrk -c 100 -d 20 http://localhost:3000
Running 20s test @ http://localhost:3000
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.62ms    2.10ms  37.33ms   90.79%
    Req/Sec    20.25k     2.99k   27.95k    73.50%
  807938 requests in 20.06s, 70.12MB read
Requests/sec:  40285.83
Transfer/sec:      3.50MB
```

Thank you!

**Comment by sdogruyol** [comment]
@genki thanks a lot!

Meanwhile if you want more performance (more than 2x) you can disable `logging`.

```crystal
require "kemal"
logging false

get "/" do
  "test"
end
```

**Comment by genki** [comment]
@sdogruyol thx!
Now it achieves 62439.80 rps. (Other processes may have affected the result)
Amazingly fast :)

**Comment by sdogruyol** [comment]
@genki thanks a lot :+1:

**Comment by greentornado** [comment]
`Running 30s test @ http://0.0.0.0:3000
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.50ms    2.02ms  26.50ms   78.10%
    Req/Sec     4.36k   468.25     8.12k    74.67%
  1564425 requests in 30.10s, 180.53MB read
  Socket errors: connect 0, read 261, write 0, timeout 0
Requests/sec:  51968.70
Transfer/sec:      6.00MB`

Well i got 50k rps on my old 2011 i7 mb pro ;) Faster than clojure and play framework on a simple hello world. impressed

**Comment by faustinoaq** [comment]
@genki @greentornado Hi guys, I'm a bit late here 😅  if you want to go even faster try `reuse_port` feature:

```crystal
require "kemal"

get "/" do
  "test"
end

Kemal.config do |cfg|
  cfg.serve_static = false
  cfg.logging = false
end

Kemal.run { |cfg| cfg.server.bind(reuse_port: true) }
```

Then run:

```sh
crystal build --release --no-debug server.cr

export GC_MARKERS=1

export KEMAL_ENV=production

for i in $(seq 1 $(nproc --all)); do
  ./server &
done

wait
```

Se more on [TFB repository](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Crystal/kemal#crystal-kemal) and [TFB page](https://www.techempower.com/benchmarks/previews/round15/#section=data-r15&hw=ph&test=fortune&f=zg1ucn-yy362n-ziig1r-zik0y7-v23chr-zijunz-xan9xa-e7)

**Comment by greentornado** [comment]
@faustinoaq can you create a sample github ?

I got some error:

`
🚀  crystal build --release --no-debug src/demo_server.cr
Error in src/demo_server.cr:15: instantiating 'Kemal:Module#run()'

Kemal.run { |cfg| cfg.server.bind(reuse_port: true) }
      ^~~

in src/demo_server.cr:15: instantiating 'Kemal:Module#run()'

Kemal.run { |cfg| cfg.server.bind(reuse_port: true) }
      ^~~

in src/demo_server.cr:15: undefined method 'bind' for Nil (compile-time type is (HTTP::Server | Nil))

Kemal.run { |cfg| cfg.server.bind(reuse_port: true) }
                             ^~~~

Rerun with --error-trace to show a complete error trace.

`

**Comment by faustinoaq** [comment]
@greentornado What version of kemal and crystal are you using?

**Comment by faustinoaq** [comment]
> @faustinoaq can you create a sample github ?

Here you are! https://github.com/faustinoaq/kemal-reuse-port 😄

**Comment by greentornado** [comment]
@faustinoaq  i'm using 

Crystal 0.24.1 (2017-12-26)

LLVM: 5.0.1
Default target: x86_64-apple-macosx

shards:
  kemal:
    github: kemalcr/kemal
    version: 0.22.0

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  radix:
    github: luislavena/radix
    version: 0.3.8

**Comment by sdogruyol** [comment]
@greentornado please try

```crystal
Kemal.run { |cfg| cfg.server.not_nil!.bind(reuse_port: true) }
```

**Comment by greentornado** [comment]
@sdogruyol  I tried and it complied well now.
