### ISSUE TITLE
kemalcr.com down :/

### ISSUE THREAD

**Issue by jmoriau** [sdogruyol/kemal#77]
I tried to read the doc at kemalcr.com but it seems to be unresponsive :/

**Comment by sdogruyol** [comment]
@jmoriau have you tried http://kemalcr.com ?

**Comment by bahattincinic** [comment]
**"Documentation"** link is broken ? https://github.com/sdogruyol/kemal/blob/gh-pages/_config.yml#L21

**Comment by askn** [comment]
thanks @bahattincinic :+1:

**Comment by jmoriau** [comment]
Now I feel silly but when I clicked on it earlier it wouldnt load at all, thought it was down :/
Sorry
