### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by jmoriau** [sdogruyol/kemal#80]
Hello,

I've been reading the documentation and browsing the code for a few days and it looks really cool ( :+1: ) so I was thinking of implementing a custom logger but I think a few things wouldn't work right now:

First here

    config = Kemal.config
    if config.logging
      logger = Kemal::LogHandler.new
      config.logger = logger

Could we maybe specify our own logger class in something like `config.logger_class` (I don't even know if Crystal would support that) and then it would get instantiated? (Of course our logger will have a `write` method)

And then here:

    rescue ex
        Kemal::LogHandler::INSTANCE.write "Exception: #{ex.to_s}\n"
        return render_500(context, ex.to_s)

You call your logger explicitly instead of `Kemal.config.logger.write` (I'm sure it's on purpose, I just don't see it, I'm still not very comfortable with Crystal)

Do you think I could achieve this without too much trouble or is it just not possible ?

**Comment by sdogruyol** [comment]
Hey @jmoriau ,

You can easily write your logger:

- First you can disable the default logger like `logging false`
- Create your own `LogHandler` and add it to handlers like `add_handler MyLogHandler.new`

Since LogHandler is practically a `HTTP::Handler` anything that is a `HTTP::Handler` can be used

**Comment by jmoriau** [comment]
Oh ok great thanks!

**Comment by jmoriau** [comment]
Hi

So I tried what you suggested, but I have 2 issues  :sob:  :

Even with logging = false

    require "kemal"

    get "/" do
      "Hello"
      raise "World"
    end

    Kemal.config.logging = false

The default `Kemal Logger` will log exceptions, most likely because it's still called here ?

    rescue ex
        Kemal::LogHandler::INSTANCE.write "Exception: #{ex.to_s}\n"

=>

    kemal-api git:(master) ✗ crystal build --release src/kemal-api.cr && ./kemal-api
    Exception: World

And the second issue is tied to the first, how can my logger be called on each exception if the default logger is called explicitly instead of `Kemal.config.logger.write` ?

Maybe I just don't get it ? What am I missing ? :confused:

**Comment by sdogruyol** [comment]
Nice one :+1: You are right.

Need to decouple the exception from `Kemal::Logger`

**Comment by jmoriau** [comment]
Oh cool then I spotted another place where the default logger is used explicitly:

    macro log(message)
      Kemal::LogHandler::INSTANCE.write "#{{{message}}}\n" if Kemal.config.logging
    end

:smile:

**Comment by sdogruyol** [comment]
@jmoriau great job :+1: 

The logging system needs to be more abstracted.

**Comment by sdogruyol** [comment]
@jmoriau i've started decoupling the logger.

**Comment by jmoriau** [comment]
@sdogruyol Awesome can't wait :+1:

**Comment by sdogruyol** [comment]
I completed decoupling the logger.

You can create your own logger which inherits from `Kemal::BaseLogHandler ` and then use it as your logger with `Kemal.config.logger = MyLogHandler.new` :+1:

**Comment by jmoriau** [comment]
Great thanks a lot! :+1:
