### ISSUE TITLE
kemal-chat crystal run error

### ISSUE THREAD

**Issue by slmkrnz** [sdogruyol/kemal#81]
has it got any new version ? 
crystal run src/kemal_chat.cr 
Error in ./libs/kemal/kemal.cr:5: instantiating 'OptionParser:Class#parse!()'
  OptionParser.parse! do |opts|
               ^~~~~~
in /usr/local/Cellar/crystal-lang/0.11.1/src/option_parser.cr:54: instantiating 'parse(Array(String))'
    parse(ARGV) { |parser| yield parser }
    ^~~~~
in /usr/local/Cellar/crystal-lang/0.11.1/src/option_parser.cr:54: instantiating 'parse(Array(String))'
    parse(ARGV) { |parser| yield parser }
    ^~~~~
in ./libs/kemal/kemal.cr:5: instantiating 'OptionParser:Class#parse!()'
  OptionParser.parse! do |opts|
               ^~~~~~
in ./libs/kemal/kemal.cr:7: instantiating 'Kemal:Module#config()'
      Kemal.config.port = opt_port.to_i
            ^~~~~~
in ./libs/kemal/kemal/config.cr:5: instantiating 'Kemal::Config:Class#new()'
    INSTANCE = Config.new
                      ^~~
instantiating 'Kemal::Config#initialize()'
in ./libs/kemal/kemal/config.cr:13: instantiating 'read_file()'
      read_file
      ^~~~~~~~
in ./libs/kemal/kemal/config.cr:37: undefined method 'working_directory' for Dir:Class
      path = File.expand_path("config.yml", Dir.working_directory)

**Comment by sdogruyol** [comment]
You need to use at least Crystal `0.11.0`.

**Comment by slmkrnz** [comment]
my version is crystal-lang-0.11.1, 
I suppose it is latest version.

**Comment by sdogruyol** [comment]
Can you share your `shard.yml` ?

**Comment by slmkrnz** [comment]
I have not changed
name: kemal-chat
version: 0.1.0

dependencies:
  kemal:
    github: sdogruyol/kemal
    branch: master

authors:
  - Sdogruyol <dogruyolserdar@gmail.com>

license: MIT

**Comment by sdogruyol** [comment]
I'm running the same exact sample with Crystal `0.11.1`.

**Comment by slmkrnz** [comment]
problem continues, and I run crystal base functions, but Kemal not run for me

**Comment by sdogruyol** [comment]
I can't say more without seeing any code.

**Comment by slmkrnz** [comment]
![screen shot 2016-02-12 at 16 12 14](https://cloud.githubusercontent.com/assets/5344046/13009164/809f185c-d1a3-11e5-8255-30d63ce2a778.png)

**Comment by sdogruyol** [comment]
Oh! That repo is probably outdated.

I'll update it asap :+1:

**Comment by sdogruyol** [comment]
Updated the repo. 

You need to do

`shards update`

Please open the next issue in that repo since the isssue is not related to Kemal itself. 

P.S: You can check https://github.com/f/kemal-react-chat for Kemal + React chat app

**Comment by slmkrnz** [comment]
Thanks that works :+1:
