### ISSUE TITLE
Filter middleware is order dependent

### ISSUE THREAD

**Issue by jmoriau** [sdogruyol/kemal#82]
Hi again,

I was also looking at the `Kemal::Middleware::Filter` implementation and the `before` `after` will only work if `Kemal::Middleware::Filter` is the first middleware added. If another is added before this one it will silently fail.

I don't know if you wanted it specifically this way but if you want it to not be order dependent you could replace these lines in `kemal/middleware/filters.cr`:

    def add_filters
      Kemal.config.add_handler Kemal::Middleware::Filter.new
    end

    def before(path = "*", options = {} of Symbol => String, &block : HTTP::Server::Context -> _)
      filter = Kemal.config.handlers.first as Kemal::Middleware::Filter
      filter.add :before, path, options, &block
    end

    def after(path = "*", options = {} of Symbol => String, &block : HTTP::Server::Context -> _)
      filter = Kemal.config.handlers.first as Kemal::Middleware::Filter
      filter.add :after, path, options, &block
    end

With these (very little change but would make it order independent and would remove the need to call `add_filters` explicitly instead it will be called lazily if it hasn't been called before) =>

    def add_filters
      unless filter = Kemal.config.handlers.any? { |handler| handler.is_a? Kemal::Middleware::Filter }
        filter = Kemal::Middleware::Filter.new
        Kemal.config.add_handler filter
      end
      filter
    end

    def before(path = "*", options = {} of Symbol => String, &block : HTTP::Server::Context -> _)
      filter = (Kemal.config.handlers.find { |handler| handler.is_a? Kemal::Middleware::Filter } || add_filters) as Kemal::Middleware::Filter
      filter.add :before, path, options, &block
    end

    def after(path = "*", options = {} of Symbol => String, &block : HTTP::Server::Context -> _)
      filter = (Kemal.config.handlers.find { |handler| handler.is_a? Kemal::Middleware::Filter } || add_filters) as Kemal::Middleware::Filter
      filter.add :after, path, options, &block
    end

Again, if this is by design feel free to close this immediately, just thought I'd mention it. I doubt something as insignificant as this would be worthy of a pull request, but I could make one if necessary.

**Comment by jmoriau** [comment]
I updated it a bit more and now it's a big enough for a pull request, see #85

**Comment by sdogruyol** [comment]
Closing this for the PR.
