### ISSUE TITLE
Web Framework Benchmarks

### ISSUE THREAD

**Issue by ylluminate** [sdogruyol/kemal#83]
You may consider writing a test and submitting a PR to: https://github.com/TechEmpower/FrameworkBenchmarks

I think it would be very interesting to see Kemal getting some notoriety from such an effort!

**Comment by sdogruyol** [comment]
That'd be awesome :+1:

**Comment by Jesterovskiy** [comment]
I'll try to take it, if nobody started work on it already =)

**Comment by sdogruyol** [comment]
@Jesterovskiy that'd be great :+1:

**Comment by Jesterovskiy** [comment]
I have 2 problems in specs for FB. 
`http://127.0.0.1:3000/queries?queries=foo`
`http://127.0.0.1:3000/updates?queries=`
I'm not an expert in Crystal, so you maybe can suggest, how to handle with this. Especially with last, when queries param is empty.

**Comment by ozra** [comment]
Would be curious to see how the static file serving holds up against, say nginx, also :-)

**Comment by sdogruyol** [comment]
@ozra that'd be an interesting benchmark.

**Comment by Jesterovskiy** [comment]
@sdogruyol My PR merged :) Waiting for next Round in FB.

**Comment by sdogruyol** [comment]
Thanks a lot for your great work :heart_eyes:

**Comment by ylluminate** [comment]
Cannot wait to see! :tada:

**Comment by sdogruyol** [comment]
@Jesterovskiy ouch! I just tried to run the benchmark on my local machine and it failed.

Guess you need to update the benchmark not to use Kemal `master`. Maybe you can use Crystal 0.13.0 and Kemal 0.10.0

Here's the error.

```
Error in ./server-redis.cr:84: instantiating 'sanitizedQueryCount(HTTP::Server::Context)'
Server kemal:
Server kemal:   results = (1..sanitizedQueryCount(env)).map do
Server kemal:                 ^~~~~~~~~~~~~~~~~~~
Server kemal:
Server kemal: in ./server-redis.cr:41: undefined method '[]' for Kemal::ParamParser
Server kemal:
Server kemal:   queries = request.params["queries"] as String
Server kemal:                           ^
Server kemal:
Server kemal: ================================================================================
Server kemal:
Server kemal: Kemal::ParamParser trace:
Server kemal:
Server kemal:   ./libs/kemal/kemal/context.cr:5
Server kemal:
Server kemal:         def params
Server kemal:             ^~~~~~
Server kemal:
Server kemal:   ./libs/kemal/kemal/context.cr:7
Server kemal:
Server kemal:           @params ||= Kemal::ParamParser.new(@request)
Server kemal:           ^
Server kemal:
Server kemal:   ./libs/kemal/kemal/context.cr:7
Server kemal:
Server kemal:           @params ||= Kemal::ParamParser.new(@request)
Server kemal:           ^
Server kemal:
Server kemal:   ./libs/kemal/kemal/context.cr:7
Server kemal:
Server kemal:           @params ||= Kemal::ParamParser.new(@request)
Server kemal:           ^~~~~~~
Server kemal:
Server kemal:   ./libs/kemal/kemal/context.cr:7
Server kemal:
Server kemal:           @params ||= Kemal::ParamParser.new(@request)
Server kemal:           ^
Server kemal:
Server kemal:   ./libs/kemal/kemal/context.cr:7
Server kemal:
Server kemal:           @params ||= Kemal::ParamParser.new(@request)
Server kemal:                                          ^~~
Server kemal:
Server kemal: ================================================================================
Server kemal:
Server kemal: Error: instance variable '@params' of HTTP::Server::Context was not initialized in all of the 'initialize' methods, rendering it nilable
Server kemal:
Server kemal: Specifically in this one:
Server kemal:
Server kemal:   /home/vagrant/FrameworkBenchmarks/installs/crystal-0.12.0-1/src/http/server/context.cr:11
Server kemal:
Server kemal:         def initialize(@request : Request, @response : Response)
Server kemal:             ^~~~~~~~~~
```

**Comment by sdogruyol** [comment]
I've just updated the benchmarks and it got merged :smiley:

**Comment by ozra** [comment]
Are there any posted benches? I'm currently not in "web-code mode" but you aaalways end up having to whip up a new web app at some point, so then I'd like to go Crystal-universe on the next one, would be nice to see some numbers to build up a picture of currently avail Cr web-frameworks for when the time comes :-)

**Comment by Jesterovskiy** [comment]
@ozra in FB for Crystal you have only Crystal-raw, Moonshine and Kemal(will be in the next round). Moonshine is broken now: https://github.com/dhruvrajvanshi/Moonshine/issues/29

**Comment by ozra** [comment]
Alright, just realized the link for "FB" was here in this issue, thanks!
