### ISSUE TITLE
Hello World?

### ISSUE THREAD

**Issue by ylluminate** [sdogruyol/kemal#84]
Thought I'd give `kemal` a quick test via the getting started information this evening, but ran into an apparent wall.  When I get to the execution stage after a seemingly successful compilation, and execute the binary, I get no output whatsoever.  

`src/kemal_test.cr` contains:
```
require "kemal"

get "/" do
  "Hello World!"
end
```

Any idea what may be going on here or where would I start to troubleshoot such a seemingly simplistic issue?

**Comment by sdogruyol** [comment]
The logger is currently being rewritten on `master`.

Could you please use Kemal `0.9.0`?

**Comment by ylluminate** [comment]
What's the correct method of defining `0.9.0` in the `shard.yml`?

**Comment by sdogruyol** [comment]
```yaml
dependencies:
  kemal:
    github: sdogruyol/kemal
    version: 0.9.0
```

**Comment by ylluminate** [comment]
Interesting, I did that as well, but still getting same nil result upon exec of the compiled bin.  Sounds crazy, but can you throw up a working repo of a demo for the getting started?  Or just a couple gists with the appropriate files?  Very odd that this is just seeming to give zero feedback even on 0.9.

**Comment by sdogruyol** [comment]
This is a full blown real time chat app https://github.com/f/kemal-react-chat built on Kemal
