### ISSUE TITLE
Config to prevent Kemal server running.

### ISSUE THREAD

**Issue by arcage** [sdogruyol/kemal#86]
HTTP server of Kemal always runs even if `exit()` is called explicitly, because `server.listen` is called in `at_exit`.

However, sometimes I want Kemal to exit without `server.listen`.
For example:
- Illegal command-line parameters are given.
- Another process of same Kemal app is already running.

Do you think how about adding `Kemal.config.run` property?
It should be `true` by default to cause no change to default behavior.
When it is `false`, Kemal silently exits without service.

```
if already_running?
  Kemal.config.logger.write "[#{Kemal.config.env}] another process is running.\n" if Kemal.config.logger
  Kemal.config.run = flase
  exit(1)
end
```

It is possible by adding a few lines to "kemal.cr" and "kemal/config.cr" .
I have tested it in [my forked branch](https://github.com/arcage/kemal/tree/add-config-run).

**Comment by sdogruyol** [comment]
I've been thinking about this for a while. Sounds like a good idea but still there's work to do before implementing this behavior.

Currently i'm decoupling the default logger to be replacelable.

**Comment by jmoriau** [comment]
@sdogruyol  Also would it be possible to not start the server if an unhandled exception happened before `at_exit` is reached ? Because for now as soon as this happens it jumps to `at_exit` and starts the server anyway.

**Comment by arcage** [comment]
@sdogruyol I see.
I also think the replaceable(customizable) logger is very useful feature.
Please consider this when you can be available.

**Comment by sdogruyol** [comment]
@arcage i've implemented pluggable logger behaviour please see https://github.com/sdogruyol/kemal/issues/80 for more info. 

P.S: I havent documented it yet :disappointed:

**Comment by arcage** [comment]
@sdogruyol Thanks. I'll try it.

**Comment by sdogruyol** [comment]
With version `0.11.0` `Kemal` won't run until you told him to run with `Kemal.run`. See the release notes here With version `0.11.0` `Kemal` won't run if there's an exception. Be sure to read the release notes https://github.com/sdogruyol/kemal/releases/tag/v0.11.0
