### ISSUE TITLE
[Docs] Views: Location path

### ISSUE THREAD

**Issue by Fahrradflucht** [sdogruyol/kemal#88]
In the example for rendering ecr views on http://kemalcr.com/docs/views/ the path to the view is specified as ```views/hello.ecr```.

I followed the example, created ```my_app/src/views``` and put ```hello.ecr``` there. When you try to build from the project root, following the example on http://kemalcr.com/docs/getting_started/, this won't work because the path needs to be ```src/views/hello.ecr```.

I didn't just fixed this in case I did something wrong. So, am I right? xD

**Comment by sdogruyol** [comment]
Yeah you are right. In that example the `view` folder doesn't reside in `src`. 

Putting the folder inside `src` is the correct way.
