### ISSUE TITLE
How can the context be Nil/False in `call(context)` from the `RouteHandler` ?

### ISSUE THREAD

**Issue by jmoriau** [sdogruyol/kemal#90]
Hi,

I'm sorry to annoy you again but I couldn't resist, I spent a few hours on it but couldn't figure out how in this method:

    def call(context)
      context.response.content_type = "text/html"
      response = process_request(context)
      response || call_next(context) # <========== this line
    end

From file `kemal/route_handler.cr` line 16

The `|| call_next(context)` would ever be reached ?

The `response` comes from `process_request`:

    def process_request(context)
      url = context.request.path.not_nil!
      Kemal::Route.check_for_method_override!(context.request)
      lookup = @tree.find radix_path(context.request.override_method as String, context.request.path)
      if lookup.found?
        route = lookup.payload as Route
        context.request.url_params = lookup.params
        begin
          body = route.handler.call(context).to_s
          context.response.print body
          return context # <================== this return
        rescue ex
          return render_500(context, ex.to_s) <================== this return
        end
      end
      # Render 404 unless a route matches
      return render_404(context) <================== this return
    end

The 3 `returns` above, all return the `context` object that was passed as the arg to the `process_request` method.

Also if the `context` was `Nil` the `process_request` wouldn't be reached so it's safe to assume the context passed to `process_request` is not `Nil` so when this same context is returned from `process_request` to `call` the `|| call_next` part would never be reached either right?

Even if it was `Nil` or `False` what could there be after this since the `RouteHandler` is added by Kemal in `at_exit` as the last middleware just before launching the server?

I hope I'm not just wasting your time with useless questions but it's driving me crazy :confused:

**Comment by sdogruyol** [comment]
Nice question :+1: You are actually correct.

But since `RouteHandler` is also a middleware itself it was designed to behave like that (even if it doesnt ever get to `call_next`). 

I guess we can remove that `call_next` after doing some testing.

**Comment by jmoriau** [comment]
Ah ok now I feel better :smile: thanks!

PS: sorry it wasn't really an issue more like curiosity.

**Comment by sdogruyol** [comment]
:+1:
